### ISSUE TITLE
1.1 Row selection (single/multiple)

### ISSUE THREAD

**Issue by limonte** [vaadin/px-data-grid#1]
Add `single-selection` property with `default: false` to `vaadin-grid-selection-column`:

```html
<px-data-grid-selection-column single-selection>
</px-data-grid-grid-selection-column>
```

- when switching from `single-selection` to `multi-selection` it should persist the selection
- when switching from `multi-selection` to `single-selection` and there was 1 selected item, it should persist the selection
- when switching from `multi-selection` to `single-selection` and there were 2 or more selected items, it should clear the selection

**Comment by alump** [comment]
User can multi and single select. But there is still talks about using radio buttons (even that those would behave un-radiobutton like). So I will make new ticket if/when radio buttons will be used.
