### ISSUE TITLE
User defined columns: add warnings if path or name missing

### ISSUE THREAD

**Issue by limonte** [vaadin/px-data-grid#105]
Separated from #100 

@Toshegg 

> Need to throw warning at least if path isn't passed, because user can define column.name as 'First Name', for example, since header is not required parameter, what can cause errors.

**Comment by drewharvey** [comment]
I think this was fixed in https://github.com/vaadin/px-data-grid/commit/409eea4a5af7ba4706f9fe7fc3d4fd07dec4f863

px-data-grid.html (line: 799)
