### ISSUE TITLE
'Table Actions' dropdown

### ISSUE THREAD

**Issue by limonte** [vaadin/px-data-grid#11]
UI specs:

![image](https://user-images.githubusercontent.com/6059356/32550322-4f5bf26a-c495-11e7-9331-b18046b521ca.png)

In scope of this task only menu items with column names should be implemented. 

`px-dropdown` should be under the hood.

There should be a `check` icon near each column which is visible. Click on each menu item should toggle the visibility of corresponding column. 

See the Complex example of `px-data-table`: https://www.predix-ui.com/#/elements/data-table/px-data-table

**Comment by alump** [comment]
After https://github.com/vaadin/px-data-grid/pull/110 this is more look'n feel issue.

**Comment by alump** [comment]
Functionality is there, so closing this. Possible styling issues to be handled later.
