### ISSUE TITLE
Find better way to identify columns than names

### ISSUE THREAD

**Issue by alump** [vaadin/px-data-grid#111]
Now we use names of columns to identify columns. Fine this is something we also show at table actions menu, and so should be unique, I'm not sure if this the best way to do it. We do have way to defined header text with different property, so you can still have empty headers and do not break this magic.

**Comment by limonte** [comment]
We need this feature for advanced filtering. Table actions doesn't work properly as well in edge cases like:

```js
columns: [
  {
    name: 'Birth Date (date)',
    path: 'birth_date',
    type: 'date',
  }
  {
    name: 'Birth Date (string)',
    path: 'birth_date',
    type: 'string',
  }
]
```

## Proposal

Introduce the `id` for columns.

- `id` can be provided by user, e.g.
```js
columns: [
  {
    name: 'Birth Date (date)',
    path: 'birth_date',
    type: 'date',
    id: 'birthdate-date'
  }
  {
    name: 'Birth Date (string)',
    path: 'birth_date',
    type: 'string',
    id: 'birthdate-string'
  }
]
```

- if `id` isn't provided by user it will be generated automatically in format `path[type`, e.g. `birth_date[string]`

- in case there are more than one columns with the same path-type combinations and user didn't provide ids manually, the warning will be thrown: `"Warning! There are more than one columns with birth_date path and string type, please provide id's for those columns"`
