### ISSUE TITLE
Spinner stays visible in case of network issues

### ISSUE THREAD

**Issue by limonte** [vaadin/px-data-grid#112]
![recorded](https://user-images.githubusercontent.com/6059356/33607964-778bb8ec-d9cb-11e7-85c8-1b2588f5e471.gif)

### Steps

- go to remote data provide example
- go to offline mode
- scroll to second page
- go to online mode

### Actual

Spinner stays visible

### Expected

Spinner is hidden in both cases: successful and failed ajax requests to remote data source.

**Comment by alump** [comment]
Can application ask grid to not show spinner anymore? As in case of network issue, error handling should be left to remote provider.

**Comment by alump** [comment]
@Toshegg Now we have the callback for success case, but how should application handle networks errors? Responding with empty item set? Or is there other way that application can ask to get rid of spinner.

**Comment by limonte** [comment]
Depends on https://github.com/vaadin/vaadin-grid/issues/1165

**Comment by Aileen-H** [comment]
PRIORITY 3

**Comment by alump** [comment]
@limonte - will this be included to vaadin-grid soon? Is is API change?

**Comment by limonte** [comment]
> will this be included to vaadin-grid soon? Will it require API change?

Yes, API change is required and it will be shipped in vaadin-grid v6. For now, it's a data-provider responsibility to handle AJAX request failures.

> Responding with empty item set?

Empty item set it is.
