### ISSUE TITLE
Unhandled exception when row is clicked after disabling Selectable

### ISSUE THREAD

**Issue by drewharvey** [vaadin/px-data-grid#129]
![selection-toggle-exception](https://user-images.githubusercontent.com/2496955/33786753-3ceb1d80-dc1f-11e7-8c64-290f30f1334b.gif)

Repro in the "Basic examples" demo:

1. Set Selectable to true.
1. Set Selectable to false.
1. Click on any row.
1. Exception is thrown.

**Comment by alump** [comment]
when we toggle selectable, the disconnectCallbacks doesn't get called on selection column

**Comment by drewharvey** [comment]
Looks like this._grid is not defined after super.disconnectedCallback() gets called in px-data-grid-selection-column.disconnectedCallback function.  This causes it to skip the block where the listeners are removed.
