### ISSUE TITLE
Horizontal separator lines should be $gray4

### ISSUE THREAD

**Issue by 212324963** [vaadin/px-data-grid#133]
**Currently:**
Separator lines are colored $gray5

**Expected:** 
Separator lines are colored $grey4

Header and Footer lines remain $gray10

![screen shot 2017-12-11 at 9 59 12 am](https://user-images.githubusercontent.com/25111262/33846066-4fa05322-de5a-11e7-99af-05910bdaaf40.png)

**Comment by 212324963** [comment]
Here is a revised drawing, that show better that the thin line is the one we are talking about. 
![screen shot 2017-12-11 at 3 11 49 pm](https://user-images.githubusercontent.com/25111262/33858716-a7b4be4c-de85-11e7-9765-036a58dda000.png)

**Comment by alump** [comment]
This should be now fixed, and included to delivery 4
