### ISSUE TITLE
Coloring issues if stripes are applied after selection

### ISSUE THREAD

**Issue by alump** [vaadin/px-data-grid#137]
Not sure about steps needed, but looks like stripe colors might override selection color, if striping is enabled after selection.

**Comment by Toshegg** [comment]
Before turning on striped option:
![image](https://user-images.githubusercontent.com/5630034/33888815-d32359e0-df56-11e7-8cb5-310db6cce7df.png)
After:
![image](https://user-images.githubusercontent.com/5630034/33888931-37bf2b5e-df57-11e7-875b-4072d3b0169e.png)
Selection colors are different according the design specs.

**Comment by alump** [comment]
I need to ask how they reproduced the issue, I was on that telco with phone, so I might have missed something.

**Comment by alump** [comment]
Marked fixed to delivery 4
