### ISSUE TITLE
Tables with few lines has empty space

### ISSUE THREAD

**Issue by 212324963** [vaadin/px-data-grid#144]
**Current:** 
The table shows empty rows

**Expected:**
The table is only as tall as the rows it has. 

![empty_space](https://user-images.githubusercontent.com/25111262/33903216-7aed47ce-df2c-11e7-8caf-991bc610e795.png)

**Comment by alump** [comment]
Enhancement: add API call to set visual height of grid as number of rows. If it works well, it could also be the default, but only automatically applied once (application needs to recall it if after each update, if it wants the size to change).

**Comment by alump** [comment]
Assigned to Drew, to verify few complex use cases first

**Comment by alump** [comment]
autoHeight property added
