### ISSUE TITLE
1.13 Ability to highlight a row or column

### ISSUE THREAD

**Issue by limonte** [vaadin/px-data-grid#15]
Example code how to highlight a rows and columns will be provided.

### UI specs: 

![image](https://user-images.githubusercontent.com/6059356/32550980-a7e85b24-c497-11e7-8fb7-df18dee5197a.png)

**Comment by alump** [comment]
Fix user defined columns

**Comment by alump** [comment]
I think best way to make this work with application defined columns would be just to move column definitions to property. This way we could use templates with dom-ifs. And have all the default wrappers and other bells and whistles we want.
