### ISSUE TITLE
1.14 Save & restore layout (user preferences)

### ISSUE THREAD

**Issue by limonte** [vaadin/px-data-grid#16]
There are internal APIs for sorting, filtering, column order, page size, etc. We need to expose those in order to reuse.

API for notes/comments are considered to be data, and so not included here.

- implement 2 methods `saveLayout()` and `restoreLayout()`
- an application should be able to provide the storage type
- add the example how to use it with the native `localStorage`

**Comment by alump** [comment]
Update:
`getState` style function that generated the big JS object (Something can be JSON'fied if possible)
And then matching setState(obj) version for it.

And finally `restoreState` that would go back to state last time given with `setState`.

Remember to deep clone these objects, always when receiving from of giving to outside.
