### ISSUE TITLE
Multi Sort uses the wrong priority sequence

### ISSUE THREAD

**Issue by 212324963** [vaadin/px-data-grid#181]
**Current:**
Clicking one column header and then another column header marks the last clicked column header with a 1, and gives it the highest sorting priority.  

**Expected:** 
The first clicked column has the highest priority.

**Comment by alump** [comment]
Not sure how much work it will be to change this. Needs to be checked.

**Comment by alump** [comment]
Is is doable by overriding _onSorterChanged (on sort-mixing of vaadin-grid) to use push, not unshift. But this would be overriding private method, that is ugly. Other option would be to catch the sorter event, and redirect it to our own handler, but again same issue.

So to fix this we need to modify private behavior of vaadin-grid, which can easily break at any point when vaadin-grid dependency is updated.

**Comment by alump** [comment]
Trying to see if I can get this resolved while I implement px-data-grid-sorter.html

**Comment by alump** [comment]
No resolved to 5A, maybe will be to 5B. Way to fix this is little ugly (replacement of event handling in vaadin-grid when header clicked).
