### ISSUE TITLE
Column separator line is not supposed to show up when only selection is enabled. 

### ISSUE THREAD

**Issue by 212324963** [vaadin/px-data-grid#182]
**Current:**
Column separator line shows up as soon as row selection is enabled. 
![screen shot 2017-12-18 at 10 47 04 am](https://user-images.githubusercontent.com/25111262/34122304-d213b304-e3e0-11e7-9bca-7a172e5cfdaa.png)

**Expected:**
Line is only present when Selection and Column Freezing is enabled at the same time.
![screen shot 2017-12-18 at 10 45 58 am](https://user-images.githubusercontent.com/25111262/34122252-a920876a-e3e0-11e7-8d4e-b650e025e44c.png)

**Comment by alump** [comment]
This will lead the mysteriously cut text and field. If user scrolls other columns under the selection column, as mentioned before. Do you really want this? @212324963

**Comment by alump** [comment]
@212324963 an idea... how about we only show that line when horizontal scroll position is not zero. This way in cases where there is no horizontal scroll, or user haven't scrolled yet. the line is not visible, but as soon as user scroll the line becomes visible. This way it not there when not needed.

**Comment by alump** [comment]
We will also have the chevron column now that should be frozen, so amount of "always" frozen columns is increasing. For this reason this auto hide feature might be nice.
