### ISSUE TITLE
Radio buttons and Checkboxes need to be vertically centered

### ISSUE THREAD

**Issue by 212324963** [vaadin/px-data-grid#184]
**Current:**
Affordances sit too low
![screen shot 2017-12-18 at 12 21 53 pm](https://user-images.githubusercontent.com/25111262/34126354-2226a0a6-e3ee-11e7-92df-17c51cd48f07.png)

**Expected:**
Affordances are visually centered.
![screen shot 2017-12-18 at 12 24 46 pm](https://user-images.githubusercontent.com/25111262/34126457-7b9ef02a-e3ee-11e7-990f-abc4506cf661.png)

**Comment by alump** [comment]
When fixing this, notice row height change made by https://github.com/vaadin/px-data-grid/pull/187

**Comment by alump** [comment]
Notice that we can not pixel perfectly center these native input components on all platforms. As they are different size on each. Also these are on most of the systems bigger than space left after wanted row height (40px) and wanted padding. For this reason we can aim some browsers/os combos, but we can't make this perfect on each.
