### ISSUE TITLE
1.17 Expandable Table Row

### ISSUE THREAD

**Issue by limonte** [vaadin/px-data-grid#19]
Existing functionality in `<vaadin-grid>`

Click on a row affordance, display area below the row with additional information. Will be flexible to display any component (such as a chart or a graph) inside the expanded area.

Provide an example.

### UI specs

![image](https://user-images.githubusercontent.com/6059356/32551556-9c9d3882-c499-11e7-97fb-ada8e55b29bb.png)

**Comment by alump** [comment]
Tagging to delivery 5, just so that we do not forget this.

**Comment by alump** [comment]
Assigned to @drewharvey. To be implemented by using similar template as vaadin-grid, just passing it via px-data-grid to vaadin-grid.

And then API for application to ask item to expanded and collapsed.

**Comment by alump** [comment]
Included to delivery 5 A
