### ISSUE TITLE
Bottom line consists of both a light and a dark gray line

### ISSUE THREAD

**Issue by 212324963** [vaadin/px-data-grid#190]
**Current:**
Bottom line is consisting of a double line

![screen shot 2017-12-18 at 1 10 30 pm](https://user-images.githubusercontent.com/25111262/34128299-118d2484-e3f5-11e7-8467-e3de9b98724b.png)

**Expected:**
Bottom line is made up of only a single dark gray line

**Comment by alump** [comment]
Ok we found way to do this, but one questions:

Should this be only applied when we auto-height the grid? As not having border under last row looks little unbalanced when there is empty space below it (read: grid is bigger than than the rows).

**Comment by 212324963** [comment]
**Auto-height** (Grid is less tall when there are less items)
Suggest to hide the light gray line to avoid double line

**Fixed-height:** (State where the rows are not filling up the entire height of the grid container)
Last row keeps line at it's bottom to avoid the appearance of a very tall and empty row.

**Comment by alump** [comment]
Good, this is how @Toshegg already implemented it. Should included in tomorrow's release.
