### ISSUE TITLE
Pagination: When only one page is present hide pagination UI

### ISSUE THREAD

**Issue by 212324963** [vaadin/px-data-grid#193]
Currently:
Pagination UI is present at all times

Expected:
When only one page is present, pagination UI is hidden

**Comment by drewharvey** [comment]
This seems to contradict issue listed in #192.  Can you elaborate?

**Comment by alump** [comment]
Pagination UI also has the page size dropdown (user can not change it when only one page shown?). And size can also get less than 1 page when filtering etc. If we start to hide pagination UI we need clear rules when it should be hidden and when not.

**Comment by 212324963** [comment]
T hank you for your questions. We suggest to hide the paging <- 1 -> UI when there is only one page of rows. It seems to make sense to keep the page size dropdown in all cases.

**Comment by alump** [comment]
Ok, @drewharvey - do you magic

**Comment by alump** [comment]
I think this has been now fixed
