### ISSUE TITLE
Header: Three dot affordance is too tall and sits too low

### ISSUE THREAD

**Issue by 212324963** [vaadin/px-data-grid#220]
**Current:**
That three dots are too tall and sit too low.

![screen shot 2017-12-20 at 12 53 10 pm](https://user-images.githubusercontent.com/25111262/34228236-ea869398-e584-11e7-9f0d-8439a2d7682a.png)

**Expected:**
The three dots are as tall the the capital letters. 

![screen shot 2017-12-20 at 12 50 11 pm](https://user-images.githubusercontent.com/25111262/34228116-67292862-e584-11e7-8608-e5d2a6711850.png)

**Comment by alump** [comment]
@Toshegg - check how to style dropdown icon to smaller, should be 10px or something
