### ISSUE TITLE
2.2 Custom renderer support

### ISSUE THREAD

**Issue by limonte** [vaadin/px-data-grid#23]
As a Predix application developer I will be able to use vaadin-grid’s column <template> to allow application to provide of custom JavaScript renderers.

**Comment by alump** [comment]
Feature is there, but better example needed. To delivery 2.

**Comment by alump** [comment]
Move to delivery 3 as column API change

**Comment by alump** [comment]
We have example, and API, but to be finalized in next delivery.

**Comment by alump** [comment]
Moving to delivery 5, as this is now more documentation example

**Comment by alump** [comment]
We will have 3 examples soon, this can be closed soon.

**Comment by alump** [comment]
Support now included, documentation example might get own ticket later.
