### ISSUE TITLE
Remove unnecessary css imports

### ISSUE THREAD

**Issue by katemenkhaus** [vaadin/px-data-grid#238]
Files `px-data-grid-dark-theme.scss` and `px-data-grid-light-theme.scss`
- It looks like `px-defaults-design` and `px-mixins-design` are not needed in this file. 

File `px-data-grid.scss`
- In the files that`include="px-data-grid-styles` I don't see the classes in these files being used `px-helpers-design`, `px-flexbox-design`, `px-viewport-design`, `px-layout-design`, `px-button-group-design`, `px-spacing-responsive-design`, and `px-widths-responsive-design`. If that is true, these imports can be removed. 
- Need to add `px-box-sizing-design` because we define our `box-sizing: border-box;`

**Comment by Toshegg** [comment]
@katemenkhaus, we faced with a problem when we imported box-sizing-design:
you define 
```css
* {
box-sizing: inherit;
}
```
in this file, what causes `box-sizing` in some elements to be `content-box` instead of `border-box`.
To fix that we had to remove this import.

**Comment by katemenkhaus** [comment]
@Toshegg what is important that the box-sizing in set to `border-box`. It can be confusing when we have a mix of `content-box` and `border-box` as I'm sure you just saw. I do find it interesting that you are getting a mix with that import though. I would double check that you aren't setting `content-box` somewhere and it is inheriting that. Could it be inheriting from the vaddin grid?

**Comment by alump** [comment]
I say we should never import those dependencies. Not when we build on something existing (like vaadin-grid).

**Comment by alump** [comment]
Moving this to end of year delivery, as not really sure what all should be done here now.

**Comment by katemenkhaus** [comment]
We can leave the dependencies out for now. If we have problems with it later we'll handle it then.
