### ISSUE TITLE
Avoid using !important in css

### ISSUE THREAD

**Issue by katemenkhaus** [vaadin/px-data-grid#240]
Nothing will be able to over ride the `display: inline-block !important` besides another `!important` this can be a slippery slope. 
https://github.com/vaadin/px-data-grid/blob/master/px-data-grid-header-cell.html#L27
It is absolutely necessary to use an `!important` here?

**Comment by Toshegg** [comment]
@katemenkhaus, we are using `hidden` attribute, that hides element out of the box.
On the other hand, due to https://meowni.ca/hidden.is.a.lie.html, `hidden` doesn't work properly in polymer, so, user may define this rule:
```css
 [hidden] { display: none !important}
```
In order to avoid such situations, we need to use `!important` as well.

**Comment by katemenkhaus** [comment]
I missed that it was for `hidden` sorry about that.
