### ISSUE TITLE
2.4 Ability to use CSS/SASS for Theming

### ISSUE THREAD

**Issue by limonte** [vaadin/px-data-grid#25]
Add SASS -> CSS compilers for scss files https://github.com/vaadin/px-data-grid/tree/master/sass

Be aligned with https://github.com/PredixDev/px-theme/blob/master/gulpfile.js

**Comment by alump** [comment]
This can be marked done when somebody has tested using px-data-grid inside predix app, and seen theming working as wanted.

**Comment by alump** [comment]
@limonte - can this be closed now?

**Comment by limonte** [comment]
yup

**Comment by alump** [comment]
Thanks.
