### ISSUE TITLE
Custom columns demo doesn't work in IE11

### ISSUE THREAD

**Issue by limonte** [vaadin/px-data-grid#254]
Some polyfill issue :/

```
Unable to get property 'length' of undefined or null reference
```

![](https://i.imgur.com/BSIk0ie.png)

- monkey-debug what causing this issue
- add test in case the issue is in px-data-grid (most likely)
- fix

**Comment by limonte** [comment]
Fixed in https://github.com/webcomponents/shadydom/pull/205 

Waiting for Polymer team to merge and release the fix.

**Comment by limonte** [comment]
The same issue for Firefox

**Comment by alump** [comment]
Let's keep browser issue on all issues that do not repeat on all browsers, even if it's polyfill issue (and not specific to single browser)
