### ISSUE TITLE
Auto-filter doesn't work when filtering by Display Month e.g. May in Birthdate

### ISSUE THREAD

**Issue by Aileen-H** [vaadin/px-data-grid#259]
![screen shot 2017-12-27 at 1 46 38 pm](https://user-images.githubusercontent.com/21231643/34394151-3b6f0fd8-eb0c-11e7-9ea9-986ac2ff024f.png)
Auto-filter doesn't work when finding Display Month e.g. May in Birthdate
![screen shot 2017-12-27 at 1 46 50 pm](https://user-images.githubusercontent.com/21231643/34394147-36141682-eb0c-11e7-81c1-2b8f428abb30.png)

**Comment by alump** [comment]
The value of that cell is actual datetime, not really the string you see there. If you think we should use toString conversion of date to autofilter always, then we could do this, but then you would also find those rows with query "00" as it's there in string presentation of date. I think this would easily make auto query useless, as these timestamps would start to match with any query strings with numbers.

**Comment by Aileen-H** [comment]
I figured it's looking at the actual datetime when filtering but I think  it's confusing to the user if "May" is displayed for month and they do an auto-filter looking for all rows with "May" and it doesn't appear.
I think it should work that it should find the rows which contain the string "May". If the user types in actual date format 05/19/2017 then it should filter for rows with this date string.

**Comment by alump** [comment]
The actual value in this case is 'YYYY-MM-DD' string, we just show it little funny right now. So you actually will find if you write day in that format.

If the value would be 'May 20' string, then it would as expected.

This all comes what type of date renderer and type pair application will use. And of course the values application has.

**Comment by Aileen-H** [comment]
It might be better then to show it as YYYY-MM-DD in the date field. As showing "May" and not then being able to filter by "May" is confusing.

**Comment by alump** [comment]
We do show YYYY-MM-DD in cell now, so closing this.
