### ISSUE TITLE
2.5 Ability to make some fields mandatory or not

### ISSUE THREAD

**Issue by limonte** [vaadin/px-data-grid#26]
`--px-data-table-cell-text-color--invalid` and `--px-data-table-cell-background-color--invalid` CSS variables should be added. This requirement only covers styling.

**Comment by alump** [comment]
Mandatory checks is left to be implemented by renderers

**Comment by limonte** [comment]
I assume this is done in https://github.com/vaadin/px-data-grid/pull/176
