### ISSUE TITLE
Tooltip sticks when exiting edit mode

### ISSUE THREAD

**Issue by skistz** [vaadin/px-data-grid#260]
Date is invalid tooltip sticks until you resize the browser. Tooltip should disappear when edit mode is exited.

Steps to reproduce:
-Select custom columns
-Turn on Editable
-Click pencil to edit row
-Click x to close edit mode

![image](https://user-images.githubusercontent.com/25310251/34395286-e4898128-eb13-11e7-9be4-94c288e0f8c4.png)

**Comment by alump** [comment]
Working with this...
