### ISSUE TITLE
Wrong date picker is being used

### ISSUE THREAD

**Issue by skistz** [vaadin/px-data-grid#261]
We talked about this last week, thought it was in the plan to be fixed. Documenting it here. It should be using a px-datetime component but it's using something else.

https://www.predix-ui.com/#/elements/datetime/px-datetime-picker

![image](https://user-images.githubusercontent.com/25310251/34395335-28f284ae-eb14-11e7-94f5-8592e1161aea.png)

**Comment by alump** [comment]
We tried to use it, but it was broken then (missing imports). We can try again today.

**Comment by alump** [comment]
Fixed now, there is a bug with px-datepicker dropdown, but that's issue with a component itself.
