### ISSUE TITLE
Toggle between tableData when editable

### ISSUE THREAD

**Issue by alump** [vaadin/px-data-grid#267]
- Use branch feature/px-datetime-picker
- Select columns demo
- Select more rows
- Enable editing mode
- Select "less" rows

The grid becomes empty. Somehow when toggling data and editable at the same time something breaks.

**Comment by alump** [comment]
Works for @limonte (Linux, Chrome), but not for me (MacOS, Chrome)

**Comment by Toshegg** [comment]
Can't reproduce.
