### ISSUE TITLE
extra code in shared css

### ISSUE THREAD

**Issue by katemenkhaus** [vaadin/px-data-grid#274]
In file `px-data-grid-shared.scss`

Line 18: Where is `$fa-font-path` being used? 

Line 19: setting`$inuit-enable-btn--bare` to `true` doesn't do anything if `px-buttons-design` isn't imported.   

Line 22: setting`$inuit-enable-paddings--small` to `true` doesn't do anything if `px-spacing-design` isn't imported.  

Line 25-31: This should not be explicitly set in the component. End developers are allow to use their own font. We set the `font-family` and `font-size` in the theme files. 
https://github.com/PredixDev/px-theme/blob/master/sass/px-theme.scss#L14
https://github.com/PredixDev/px-theme/blob/master/sass/px-theme.scss#L866

**Comment by alump** [comment]
I assume these are some left behinds from px-data-table, right @Toshegg ?

**Comment by Toshegg** [comment]
@alump, yes, definitely.

**Comment by alump** [comment]
Will check this tomorrow.

**Comment by alump** [comment]
When I said tomorrow, it was actually in a week, but finally cleaned the file.

@katemenkhaus can you check the PR change if I removed all the right parts:
https://github.com/vaadin/px-data-grid/pull/445/files
Thanks.
