### ISSUE TITLE
Move css out of html

### ISSUE THREAD

**Issue by katemenkhaus** [vaadin/px-data-grid#284]
Most of the css has been moved to its own sass file. 
Some that still need it are: 
`px-auto-filter-field.html`
`px-data-grid-filter-entity.html`

**Comment by alump** [comment]
First one is mistake, I though it fixed that. Second is preview of advanced filtering, will not even be there anymore in few days.

**Comment by alump** [comment]
Pull request made, my mistake.

**Comment by alump** [comment]
@katemenkhaus - so ignore px-data-grid-filter-entity.html as it will not be there anymore after we merge real advanced filtering.
