### ISSUE TITLE
Polymer serve vs. gulp serve discrepancies

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#286]
## Description:
Running into issues with a simple test file in my local env when running polymer serve vs. gulp serve.
Code snippet from the test file is below. In the first screenshot, note the polymer serve instance is: 
- missing the selectall checkbox
- getting a TypeError from data-grid-selection-column.html on page load.

Also noted 2 additional 404's on the demo page with polymer serve, but haven't noticed any functionality issue at a quick glance.

## Versions:
**Browsers:** Chrome63, FF57, safari10 and IE11
**Component/data-grid:** Master
**Polymer.version (from debugger)**: "2.4.0-rc.1"

### Simple test file comparing gulp serve(on the left) vs. polymer serve(on the right):

![multi-test-polyvsgulp](https://user-images.githubusercontent.com/10835611/34793858-a0a17cf6-f601-11e7-82ed-e853d8947558.png)

### Additional 404's on demo page load:
![demo_page_404s](https://user-images.githubusercontent.com/10835611/34793927-e4ab647a-f601-11e7-9e5e-3a9775090bdc.png)

## Test Code Snippet:
```
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DataGrid: Multi Select Test</title>
    <script src="../webcomponentsjs/webcomponents-lite.js"></script>

    <link rel="import" href="../polymer/polymer.html" />
    <link rel="import" href="../px-theme/px-theme-styles.html">
    <link rel="import" href="px-data-grid.html" />

    <custom-style>
      <style include="px-theme-styles" is="custom-style"></style>
    </custom-style>


<body>
  <dom-bind >
  <template id="table" >

  <div style="height:550px; width:1000px">
  <h2>Simple datagrid with multi select </h2>
    <px-data-grid
      table-data='[
        {"first":"Elizabeth","last":"Wong","email":"sika@iknulber.cl"},
        {"first":"Jeffrey","last":"Wong","email":"cofok@rac.be"},
        {"first":"Alma","last":"Martin","email":"dotta@behtam.la"},
        {"first":"Elizabeth","last":"Saunders","email":"seh@bibapu.gy"},
        {"first":"Willie","last":"Dennis","email":"izko@dahokwej.ci"}
        ]'
      selection-mode="multi"
      language="en"
      striped
      >
    </px-data-grid>
    </div>

  </template>
</dom-bind>

</body>
</html>

**Comment by alump** [comment]
@limonte - Can you check this? I have no idea what is happening here.

**Comment by alump** [comment]
Ok, this is high priority now, blocks other testing.

**Comment by ppeyro** [comment]
Verified in tag 1.0.3.  Looking good.
