### ISSUE TITLE
Polyfill issue in IE11 & FF57?

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#287]
## Description:
In IE11 and FF57, data-grid is rendering without the 2nd and 3rd columns and is not striped.  This happens when serving it with both gulp and polymer serve.

Test code attached below. Same test renders in Chrome and Safari10 properly(see screenshot#2 below).

## Versions:
Browsers: FF57, IE11
Component/data-grid: Master
Polymer.version (from debugger): "2.4.0-rc.1"

## Screenshot 1 (FF Gulp serve and Polymer serve):
![screen shot 2018-01-10 at 1 08 16 pm](https://user-images.githubusercontent.com/10835611/34795551-89a0a238-f607-11e7-906b-cbf6fdeb7a76.png)

## Screenshot 2 (same test file on Chrome):

![screen shot 2018-01-10 at 1 04 09 pm](https://user-images.githubusercontent.com/10835611/34795628-cb2b6026-f607-11e7-88a7-4a1f7b6f7845.png)

## Test Code Snippet:
```
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DataGrid: Multi Select Test</title>
    <script src="../webcomponentsjs/webcomponents-lite.js"></script>

    <link rel="import" href="../polymer/polymer.html" />
    <link rel="import" href="../px-theme/px-theme-styles.html">
    <link rel="import" href="px-data-grid.html" />

    <custom-style>
      <style include="px-theme-styles" is="custom-style"></style>
    </custom-style>


<body>
  <dom-bind >
  <template id="table" >

  <div style="height:550px; width:1000px">
  <h2>Simple datagrid with multi select </h2>
    <px-data-grid
      table-data='[
        {"first":"Elizabeth","last":"Wong","email":"sika@iknulber.cl"},
        {"first":"Jeffrey","last":"Wong","email":"cofok@rac.be"},
        {"first":"Alma","last":"Martin","email":"dotta@behtam.la"},
        {"first":"Elizabeth","last":"Saunders","email":"seh@bibapu.gy"},
        {"first":"Willie","last":"Dennis","email":"izko@dahokwej.ci"}
        ]'
      selection-mode="multi"
      language="en"
      striped
      >
    </px-data-grid>
    </div>

  </template>
</dom-bind>

</body>
</html>

**Comment by alump** [comment]
Sorry for throwing these to you, if you have time please check this @limonte , thanks.

**Comment by ppeyro** [comment]
Verified in tag 1.0.3.  Looking good.
