### ISSUE TITLE
Three dot "More" menu affordance is too tall and badly aligned

### ISSUE THREAD

**Issue by vonsichart200** [vaadin/px-data-grid#288]
**Current:** 
- Dots are 12 pixels tall 
- They are not properly aligned.

**Expected:**
- Dots are 8 pixels tall. As tall as the capital letters of the column labels. 
- They are expected to be aligned with the top and the bottom of the capital letters of the column labels.

![screen shot 2018-01-10 at 2 52 07 pm](https://user-images.githubusercontent.com/25111262/34799939-a0e26512-f616-11e7-8f31-35ac080ee54b.png)

**Comment by alump** [comment]
Hmm... I already changed this once, why has it reverted

**Comment by alump** [comment]
@212324963 check if this is ok now.

**Comment by Aileen-H** [comment]
1/16/18: Sami  will check and fix

**Comment by alump** [comment]
Actually I think this was fixed now? Color and safari issue has their own bugs, right @212324963 ?

**Comment by alump** [comment]
@vonsichart200 I assume this can be closed.
