### ISSUE TITLE
Header labels show wrong colors during hover and pressed

### ISSUE THREAD

**Issue by vonsichart200** [vaadin/px-data-grid#289]
Current:
- Nether three dot menu affordance nor header change color during hover and pressed states. 

Expected:
- Both three dot menu affordance and header label change color during hover and pressed states. 

![screen shot 2018-01-10 at 3 46 02 pm](https://user-images.githubusercontent.com/25111262/34801401-61c85984-f61d-11e7-9a30-f9b54fa01ad7.png)

**Comment by alump** [comment]
Based on this bug, colors are correct in dark theme?

**Comment by 212324963** [comment]
Dark theme has the same issues.

**Comment by Aileen-H** [comment]
1/16/18: Sami will fix

**Comment by alump** [comment]
IE11 causing major issues here, it's so buggy with shadowdoms that there seams to be no way to have all these 3 states working with it.
