### ISSUE TITLE
Header liable click behavior seems unintuitive

### ISSUE THREAD

**Issue by vonsichart200** [vaadin/px-data-grid#290]
**Current:**
Label clickable area have a blank spot

**Expected:**
Entire header label area is clickable

![screen shot 2018-01-10 at 3 48 49 pm](https://user-images.githubusercontent.com/25111262/34801466-c7dcc34a-f61d-11e7-9d9e-68ae05d2da03.png)

**Comment by 212324963** [comment]
Seen in Safari 11.0.2 - Seems to work fine in Chrome

**Comment by alump** [comment]
Tested on my own Safari 11.0.2, works fine with it. Can not reproduce.

**Comment by alump** [comment]
OK, Safari clicking text part doesn't work

**Comment by alump** [comment]
Still works, closing for now.

**Comment by vonsichart200** [comment]
The issue is back in Safari 11.0.2

**Comment by alump** [comment]
I tested locally master, gulp serve and safari and it works

**Comment by vonsichart200** [comment]
The dots disappear when i hover over the word/label.

**Comment by alump** [comment]
Also tested polymer serve and still works

**Comment by alump** [comment]
I can see the dots disappear on Safari

**Comment by vonsichart200** [comment]
Hm. :-)

**Comment by alump** [comment]
Make CSS workaround, hopefully this helps when we release new version

**Comment by alump** [comment]
This probably is some strange Safari bug, but hopefully just ignoring pointer events is the way to fix it.
