### ISSUE TITLE
Grouping columns should shift group labels to the left

### ISSUE THREAD

**Issue by vonsichart200** [vaadin/px-data-grid#291]
**Current:**
- Group labels are in the middle of the row, with the column label. 
![screen shot 2018-01-10 at 4 29 33 pm](https://user-images.githubusercontent.com/25111262/34802638-84cabd0e-f623-11e7-892a-66bc9052c471.png)

Expected:
- Group labels are left aligned and the label off the grouped column has been removed. 
![screen shot 2018-01-10 at 4 37 27 pm](https://user-images.githubusercontent.com/25111262/34802824-94e869ce-f624-11e7-8e8f-6224505b4820.png)

**Comment by limonte** [comment]
> the grouped column has been removed.

If we are doing so, how can users do "ungroup"? Currently the "ungroup" is placed in the column context menu: 

![](https://i.imgur.com/ptHtvF1.png)

**Comment by Aileen-H** [comment]
1/16/18: Agreed group by column should move to the left.

**Comment by vonsichart200** [comment]
The "Clear Grouping" option in the "Actions Menu" takes care of the initial concern that ungrouping would not be possible once the column, that the table has been grouped by, has been removed. This change should be good to go.

![screen shot 2018-01-25 at 3 25 39 pm](https://user-images.githubusercontent.com/25111262/35417859-089f8346-01e4-11e8-88b1-e19ef170cdd1.png)

**Comment by Aileen-H** [comment]
PRIORITY 2

**Comment by alump** [comment]
@limonte I think this is last "real" issue open in Q4, can you make code to move grouped by column to left. Already now reordering of columns should be disabled when in grouped by mode.

**Comment by vonsichart200** [comment]
Why is this labeled "Waiting for GE response"?
