### ISSUE TITLE
Column Reordering and Hidden Columns

### ISSUE THREAD

**Issue by randyaskin** [vaadin/px-data-grid#293]
Steps to reproduce:

1. Open the "Custom Columns" demo
2. Click the checkbox under the table to show the "Full Name" column
3. Turn on the toggle for "Column Reordering Allowed"
4. Attempt to move the "Full Name" column, or try to switch the position of "Age" and "First Name"

The "Full Name" column seems to be stuck in the second position and can't be reordered. Am I missing something?

Note: does not happen if you turn the Full Name column on using the Action Menu instead, so could just be an artifact of that demo checkbox.

**Comment by randyaskin** [comment]
Possibly related: if you use the "Show Full Name Column" checkbox and then the "Freeze Full Name Column" checkbox and then scroll horizontally, it freezes in place instead of moving to the first location. Again, doesn't happen if you add it with the Action Menu.

![screen shot 2018-01-10 at 5 06 07 pm](https://user-images.githubusercontent.com/2130613/34803551-bf00fcb8-f628-11e7-98ba-35b1fc8018f2.png)

**Comment by Aileen-H** [comment]
1/16/18: Agreed Sami will take a look and see if he can propose a fix in a few hours.

**Comment by alump** [comment]
Task for me: check we can run sanity checks after application has provided new rules for column, moving frozen columns to the right.

**Comment by Aileen-H** [comment]
PRIORITY 1

**Comment by alump** [comment]
Fix I made will freeze all columns left to column frozen when froze command is via API. This better to just do this, than to start reordering columns given by application. It's different use case than end user actions, as application should know better.
