### ISSUE TITLE
Multi sort: Insufficient space between checkbox and bracket

### ISSUE THREAD

**Issue by 212324963** [vaadin/px-data-grid#300]
**Current:** 
No space between checkbox and bracket

**Expected:**
5 pixel space between checkbox and bracket

![screen shot 2018-01-11 at 10 43 12 am](https://user-images.githubusercontent.com/25111262/34841195-44a0261c-f6bc-11e7-80b5-062e09dba483.png)

**Comment by alump** [comment]
This really aren't a W issue, but if this is very easy to fix, we can do it.
