### ISSUE TITLE
Sorting: Vertical separation line is always present

### ISSUE THREAD

**Issue by 212324963** [vaadin/px-data-grid#301]
**Current:** 
Vertical separation line is always present

**Expected:**
Line is only present when the user scrolls horizontally

![screen shot 2018-01-11 at 10 46 50 am](https://user-images.githubusercontent.com/25111262/34841333-c1782d38-f6bc-11e7-83fa-13a0b2b16859.png)

**Comment by alump** [comment]
Works for me, need more information. @212324963

**Comment by Aileen-H** [comment]
1/16/18: Can be closed.

**Comment by alump** [comment]
Fixed.
