### ISSUE TITLE
Disabling auto-wrap should be implemented.

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#303]
## Description:

In section 1.7 of the design spec, there is a requirement for the ability to customize a column to override auto wrap.  We don't have a property to handle that as of v1.0.3.

Discussed with Sami, he's on it.

## Screenshot:
![screen shot 2018-01-11 at 11 47 04 am](https://user-images.githubusercontent.com/10835611/34844129-4b802244-f6c5-11e7-87bf-51283c1b73d2.png)

**Comment by alump** [comment]
I think this was defined in specification so, that it's valid to except it to be option to toggle wrapping on and off. So let's add option for it. If this is really hard to do, then talk with me.

**Comment by Aileen-H** [comment]
PRIORITY 2
