### ISSUE TITLE
Toggling "Show/Hide Column" in the demo should also show/hide "Action Menu"

### ISSUE THREAD

**Issue by vonsichart200** [vaadin/px-data-grid#305]
**Current:**
A "hidden" column can only be "unhidden" when the "Action Menu" is visible

**Expected:**
The "Action Menu" should be visible as soon as "Show/Hide column" is enabled.

**Comment by alump** [comment]
- Make action default shown

**Comment by alump** [comment]
This has been fixed already. Action menu is shown by default.
