### ISSUE TITLE
Reordering an unfrozen column doesn't seem to work.

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#309]
## Description:
If you freeze a column then unfreeze it, you can't drag it to a new position even though reordering is enabled. You can replicate this on the demo but if you need the actual test file I can attach that as well.

## Version:
Browser: Chrome
Data-grid: Tag 1.0.3

## Screenshot:
![screen shot 2018-01-11 at 2 19 45 pm](https://user-images.githubusercontent.com/10835611/34850470-d37417ea-f6da-11e7-8f92-1432d0bd4a59.png)

**Comment by alump** [comment]
@Toshegg Can you ask from elements team if this is a bug in vaadin-grid, from our side the status of columns is correct, but vaadin-grid somehow does not allow to reorder unfrozen column with frozen columns or with never frozen columns.

**Comment by alump** [comment]
unfreezing column moved it to this 3rd group of columns, you can reorder unfrozen columns between each other

**Comment by alump** [comment]
Ok, if you give undefined to frozen parameter, somehow it makes this 3rd state in vaadin-grid, so I made fix that will convert undefined to false.
