### ISSUE TITLE
Editable Table - Border disappears

### ISSUE THREAD

**Issue by randyaskin** [vaadin/px-data-grid#315]
When you enter edit mode, the bottom border of the row disappears (text actually shifts down a few pixels too, so it might just be covered up):
![editable](https://user-images.githubusercontent.com/2130613/34888130-d39e0cdc-f77d-11e7-96cb-8b09bf75ce98.gif)

**Comment by randyaskin** [comment]
Note: this is only on the "Basic" demo page where there are no custom columns defined. May be moot.

**Comment by alump** [comment]
@Toshegg can you check this, to test this just select px-data-grid in basic demo, and then run ```$0.editable = true``` in console. After this you can see that when you toggle edit mode (yes nothing to edit, but ignore that) it will increase the size with 2px, and that causes this bug.

**Comment by Aileen-H** [comment]
1/16/18: Will be fixed by end of month.
