### ISSUE TITLE
Safari10: Double scrollbar when grid is resized.

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#317]
## Description:

When hiding/unhiding columns in Safari10, you get a double horizontal scrollbar.
Works fine on other browsers, even IE11!

## Version:
data-grid tag: 1.0.3
Browsers: Safari10 

## Screenshot:

![screen shot 2018-01-12 at 10 03 56 am](https://user-images.githubusercontent.com/10835611/34889022-5b2b883e-f781-11e7-8016-16e712f58651.png)

**Comment by alump** [comment]
Needs more information, code or something to reproduce.

**Comment by alump** [comment]
I think somebody said this did not happen anymore, closing.
