### ISSUE TITLE
Reordering an Expanded group table looks odd

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#319]
## Description:

1. Select groupby
2. Expand the group to open list of rows within the group.
3. Drag the column to middle of the table.

Maybe reordering should be disabled when groupby is on? Or maybe the group should be collapsed first before reordering? 

This is more of a design rather than implementation issue.

## Version:
data-grid tag: 1.0.3
Browsers: Chrome63, FF57, safari10 and IE11

## Screenshot:
![screen shot 2018-01-12 at 10 41 10 am](https://user-images.githubusercontent.com/10835611/34890052-4cd787de-f785-11e7-954a-3e335f41bc96.png)

**Comment by Aileen-H** [comment]
1/16/18: Agreed to move the grouped by column to the left. It is known that if user reorders or freezes or hides the column, then odd behaviour. May add an enhancement for the future.

**Comment by alump** [comment]
@limonte - can you look if we could add sanity check that will force the column used to be grouped by to be moved to left most data column? Could be done at same time as #441

**Comment by Aileen-H** [comment]
PRIORITY 3
