### ISSUE TITLE
Highlight of incorrect cells

### ISSUE THREAD

**Issue by randyaskin** [vaadin/px-data-grid#322]
Possibly related to #320 - in the "Custom Columns" demo if you choose the second tab with more rows and scroll down, Jesus and Thompson are highlighted even though they don't match the highlight conditions of Elizabeth and Dennis. I suspect you're re-using DOM nodes or something?
![screen shot 2018-01-12 at 11 04 24 am](https://user-images.githubusercontent.com/2130613/34890913-8a1d5404-f788-11e7-8c6b-9306d244bf39.png)

**Comment by alump** [comment]
Valid bug, we have some error still in highlighting (it's not removed from reused cells)

**Comment by alump** [comment]
Fixed in 1.1.0
