### ISSUE TITLE
Editable only works when custom columns defined

### ISSUE THREAD

**Issue by randyaskin** [vaadin/px-data-grid#324]
The Editable property doesn't do anything unless you specify custom column definitions and also include editable columns. We may not have necessarily spec'd or discussed this in the past, but the current px-data-table assumes, if you don't specify custom column definitions, that all of the columns are editable if the editable property is added on the overall table.

**Comment by alump** [comment]
Yeah, this is not feature that will be in this delivery. If this is needed it needs to be done later.

**Comment by Aileen-H** [comment]
1/16/18: Okay to include this in documentation for app developers.

**Comment by randyaskin** [comment]
Seems to be fixed in v1.1.1 - treats every column as a string / text input, which is what I would expect.

**Comment by alump** [comment]
Yes, feature is there now, BUT it's far from "perfect". And most likely it will not become perfect in this delivery.
