### ISSUE TITLE
Pagination breaks if change page size

### ISSUE THREAD

**Issue by randyaskin** [vaadin/px-data-grid#328]
On the "Pagination examples" demo page, click on page 5. Then change the page size from 10 to 30. The table goes blank (since there is no page 5 anymore) and the row count incorrectly displays "121 - 47 of 47". 

The old px-data-table automatically navigates back to page 1 when the page size is changed to avoid this situation.

**Comment by Aileen-H** [comment]
1/16/18: Drew will fix!
