### ISSUE TITLE
Can't set the height of the px-data-grid

### ISSUE THREAD

**Issue by davidrleonard** [vaadin/px-data-grid#333]
### Description

I want the grid to fill the height of some arbitrary container in my app. I don't want it to grow larger than that container's height if it has too many items, which is how `autoHeight` works. It should scroll when it hits this container's height.  If I enable `autoHeight` the px-data-grid appears to grow beyond the height of its parent container and take up as much vertical space as it needs to show all rows.

### Version

px-data-grid: v1.0.3
Browsers: Chrome64

### Reproduction

The CodePens below shows a minimal reproduction. The px-data-grid element correctly resizes its height, but the vaadin-grid inside of it does not. Perhaps I am just not configuring the grid correctly. If that's the case, let me know.

https://codepen.io/davidleonard/pen/MrXvLx?editors=1001

**Comment by davidrleonard** [comment]
Edit: Tested on the latest release of px-data-grid (v1.0.3). This problem is still present. Updated the version in the issue to match.

**Comment by alump** [comment]
Something wrong in sizing, to be investigated.

**Comment by alump** [comment]
Yeap, as setting height only applies to our wrapper, it doesn't resize vaadin-grid correct, adding iron-resizable-behavior magic...

**Comment by alump** [comment]
OK, **API CHANGE**

Replaced auto-height attribute with grid-height, the value 'auto' is the new auto height. You can also give values like '300px' that will define the height of grid.

So far relative heights do not work yet, so do not use with defining height of px-data-grid and then expect things to work. This would need more work and it's left to be done in future deliveries. Commit done soon.
