### ISSUE TITLE
Can't change pageSize for remoteDataProvider

### ISSUE THREAD

**Issue by davidrleonard** [vaadin/px-data-grid#334]
### Description

When I set a custom `pageSize` and add a `remoteDataProvider` callback function, the grid does not use the custom page size. It always asks for 50 items.

It looks like the `pageSize` property is never bound down from px-data-grid to vaadin-grid.

### Version

px-data-grid: v1.0.3
Browsers: Chrome64

### Reproduction

The CodePens below shows a minimal reproduction: https://codepen.io/davidleonard/pen/jYKGdE

**Comment by alump** [comment]
Sounds like valid bug, to be investigated.

**Comment by davidrleonard** [comment]
Confirmed fixed.
