### ISSUE TITLE
remoteDataProvider only called once

### ISSUE THREAD

**Issue by davidrleonard** [vaadin/px-data-grid#335]
### Description

Create a px-data-grid and give it a `size` of 1000:

```
<px-data-grid size="1000"></px-data-grid>
```

Set a `remoteDataProvider` function which returns the number of items requested by the grid

```
var grid = document.querySelector('px-data-grid');
grid.remoteDataProvider = (params, callback) => {
  return getDataFromAPI(params.pageSize).then(data => {
    callback(data, data.length);
  });
};
```

**Expected behavior:** The provider function will be called over and over until 1000 items have been fetched from the server.
**Actual behavior:** The provider function is only called once, and the grid does not load 1000 items.

### Version

px-data-grid: v1.0.3
Browsers: Chrome 64

### Reproduction

The CodePens below shows a minimal reproduction: https://codepen.io/davidleonard/pen/ZvRabe

**Comment by alump** [comment]
Why you set size to 100, if you have 1000 items? This feels like misuse?

**Comment by davidrleonard** [comment]
I set size to 1000. I did not set size to 100. See the codepen linked here. Size is 1000 and the grid does not request all 1000 items. It only makes one request regardless of the size and pageSize.

**Comment by alump** [comment]
Ok. so you were trying to scroll the grid, and did not ask for rows when you scrolled?

**Comment by davidrleonard** [comment]
Yes. 

David

**Comment by alump** [comment]
Works as planned.

In your code you call callback(data, data.length) - the second parameter there is the new size of grid. So you override 1000 with 100 there. Use 1000 not data.length there. Or just do not give second parameter. The reason the second parameter is there is to allow update size of grid (eg. when filtering).
