### ISSUE TITLE
"Group by" selection missing in paginated demo

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#337]
## Description
"Group by" selection is missing in the contextual menu in paginated example demo page.

## Version
data-grid tag: 1.0.3
Browsers: FF57,IE11,Chrome63,Safari10

## Screenshot
![screen shot 2018-01-12 at 5 56 32 pm](https://user-images.githubusercontent.com/10835611/34901643-fdb37608-f7c1-11e7-93ea-447abd4c9307.png)

**Comment by alump** [comment]
Wont fix, grouping is not supported in pagination mode, as those two features do not work together.
