### ISSUE TITLE
Edit button in demo pages doesn't work even with gulp serve in Safari10

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#338]
## Description

Edit button in demo pages' properties container doesn't work with **polymer serve**(which could be ok since a limited number of people will serve it up that way).  

It does work when you **gulp serve** in Chrome and FF, but not in Safari10.

Filing this issue to keep track of it until we figure out if our dev team will fix or Vaadin team.

**Comment by Aileen-H** [comment]
PRIORITY 2

**Comment by alump** [comment]
I think this has been fixed now.
