### ISSUE TITLE
Table filters modal not scaling

### ISSUE THREAD

**Issue by katemenkhaus** [vaadin/px-data-grid#349]
When I resize the screen so that the modal shrinks, the X does not scale with everything else to stay inside the modal. 

![screen shot 2018-01-16 at 10 16 34 am](https://user-images.githubusercontent.com/14931112/35004936-a6359d24-faa6-11e7-803c-698610e8e360.png)

I'm on chrome 64

**Comment by alump** [comment]
Valid issue @Toshegg, can you fix this.
