### ISSUE TITLE
Tooltip left behind in demo when switching demo page

### ISSUE THREAD

**Issue by alump** [vaadin/px-data-grid#351]
Steps:
- Open demo with editing and validation
- Edit row
- Make one of the columns invalid
- Now jump to another demo view

Expected outcome:
Tooltip is closed

Actual outcome:
Tooltip left behind

**Comment by limonte** [comment]
This is not the issue of `px-data-grid` by itself but the issue of the combination `px-demo` and `px-tooltip`

When switching between demos `px-demo` is **hiding** the previous demo, not removing it from the DOM.

On the other side, `px-tooltip` doesn't react anyhow on the parent's visibility, jsfiddle: https://jsfiddle.net/u5kjzd9h/

Theoretically, we could bring some magic like observing dummy animationend event, but the question is - should we do that on the px-data-grid size? I personally don't think so.

**Comment by Aileen-H** [comment]
@davidrleonard is this the overlay issue?

**Comment by alump** [comment]
@Aileen-H i think this issue with overlay + px-demo, as px-demo only hides stuff, so overlay has no way to get signal when to close itself.

**Comment by alump** [comment]
Closing as issue with implementation of px-demo.
