### ISSUE TITLE
Paginated Grid - autofilter broken

### ISSUE THREAD

**Issue by randyaskin** [vaadin/px-data-grid#352]
If you open the paginated table demo, turn on the auto-filter, and type something in the box, the spinner comes up but nothing happens and there's a console error:
![screen shot 2018-01-16 at 2 55 06 pm](https://user-images.githubusercontent.com/2130613/35016484-9ddc0a42-facd-11e7-872e-1f021f141c6f.png)

**Comment by alump** [comment]
I think our advanced filtering broke this, to be fixed.
