### ISSUE TITLE
Update code snippet in pagination demo

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#357]
## Description:

This came up during our bug triage meeting and also tripped me up already last Friday. 
Code sample in pagination demo page should be updated to include px-data-grid-paginated.  It only includes the px-data-grid currently.

## Version:
Data-grid: V1.1.0
Browsers: All

## Screenshot:
![screen shot 2018-01-16 at 4 19 28 pm](https://user-images.githubusercontent.com/10835611/35018988-396d193c-fad9-11e7-8f9c-9b6ae7ed24e9.png)

**Comment by alump** [comment]
Ok, Also the API part was from px-data-grid, not from px-data-grid-paginated, fixed that too
