### ISSUE TITLE
Advanced Filtering: Reset should keep modal open and set you to default state

### ISSUE THREAD

**Issue by Aileen-H** [vaadin/px-data-grid#358]
Reset button should Not cancel you out of the modal but simply reset you to the default filters (if saved) or default state.

**Comment by alump** [comment]
Reset:
- do not close dialog when clicked
- reset back to  filtering last time provided by application, or to no filter rules if filters not provided by application at anypoint
- Also call reset, not reject

**Comment by Toshegg** [comment]
@alump, according to @Aileen-H's comment I suppose it should work like so:
If you saved filters' state by checking "Save this filter set" checkbox on modal apply, "Reset" button should return filters to this state. If you haven't ever checked it during a session, filters should return to empty state. Am I right?

**Comment by alump** [comment]
Save this filter set -> emit emit save-filters with current filters, if (and after) apply is clicked. Itself will not save anything, or store any internal information that it was saved (as we can not be sure it was).
