### ISSUE TITLE
Advanced Filtering: Dropdown for Select jumps to right of modal when multiple filters

### ISSUE THREAD

**Issue by Aileen-H** [vaadin/px-data-grid#361]
Dropdown for Select jumps to right of modal when multiple filters

See screenshot
![screen shot 2018-01-16 at 5 24 55 pm](https://user-images.githubusercontent.com/21231643/35020723-5151986c-fae2-11e7-83d2-e6d8db3ae70f.png)

**Comment by Aileen-H** [comment]
NOTE: Behavior noted in Chrome

**Comment by alump** [comment]
@Toshegg - is this caused by us, or is this issue with px-dropdown?

**Comment by Toshegg** [comment]
@alump, we are using standard px-dropdown inside standard px-modal, so, I assume, that issue is on px-dropdown side

**Comment by alump** [comment]
@Aileen-H Can we get some help with this, as it's issue when px-dropdown is used inside px-modal, not sure what we can do here.

**Comment by Aileen-H** [comment]
@davidrleonard is this the overlay issue?

**Comment by Aileen-H** [comment]
This has been resolved in px-dropdown 4.5.0. Please confirm now working as expected. Thanks

**Comment by andrealperry** [comment]
Needed for Beta

**Comment by Aileen-H** [comment]
Can't recreate - closing.
