### ISSUE TITLE
Advanced Filtering: birth-date picker should not show time 

### ISSUE THREAD

**Issue by Aileen-H** [vaadin/px-data-grid#364]
Advanced Filtering: birth-date picker should not show time. Chrome browser. 
![screen shot 2018-01-16 at 5 37 06 pm](https://user-images.githubusercontent.com/21231643/35021080-ff0e708c-fae3-11e7-8fda-2577252f0461.png)

**Comment by alump** [comment]
@Toshegg - if type is date (as we now have), do not offer time in picker
