### ISSUE TITLE
5.1 Auto filtering

### ISSUE THREAD

**Issue by limonte** [vaadin/px-data-grid#37]
Basic filtering for plain strings. As Predix developer I can ask grid to present search field that is used to basic filtering of values. API hooks to get this working also on remote data source added.

UI should be implemented accordingly to provided design specs:

![image](https://user-images.githubusercontent.com/6059356/32554459-867d0d12-c4a2-11e7-9da3-14e9854e5b63.png)

![image](https://user-images.githubusercontent.com/6059356/32554484-978459b2-c4a2-11e7-98eb-2b9fb948b7b7.png)

**Comment by alump** [comment]
Generic auto filtering field is there. It's challenge will be local data.

The column autofiltering is not done yet, but with it actual filtering should be easier (as long as vaadin-grid handles value as wanted).

**Comment by alump** [comment]
See Pull Request: https://github.com/vaadin/px-data-grid/pull/81

**Comment by alump** [comment]
This works, I will do separate issue for look'n feel adjustments

**Comment by limonte** [comment]
This part of the specs isn't done, reopening

![](https://i.imgur.com/RipnJj2.png)

**Comment by alump** [comment]
That part is excluded.
