### ISSUE TITLE
Add documentation for `columns` property in px-data-grid

### ISSUE THREAD

**Issue by davidrleonard** [vaadin/px-data-grid#374]
Each object passed into the `columns` can include a number of different settings (e.g. `name`, `path`). There is no documentation in the columns property for what each setting does.

Please document:
1. What does each setting do?
2. Which settings are required, and which are optional? This will help the developer understand the minimum number of configurations necessary to use `columns`.
3. What type is expected, e.g. `string`, `number`, `boolean`
4. What is the default if no value is passed?

Example documentation block with just one setting documented...

```
/**
 * Sets the columns the grid should render. If no columns are passed, the grid
 * generates columns from the `tableData` passed in. Columns are rendered
 * in the same order as the array.
 *
 * Each column can have the following configurations. Only name and path
 * are required, all others are optional:
 *
 *   * {string} name - Name of the column.
 *   * ...
 *   * {number} [flexGrow=1] - The flex-grow CSS property to set for the column, set to a larger number to make column bigger
 *
 * Example format for a single column with all configurations used:
 * 
 * ```javascript
 * {
 *   name: 'First Name',
 *   path: 'first',
 *   hidden: false,
 *   frozen: false,
 *   required: false,
 *   flexGrow: 1
 * }
 * ```
 */
```

It is helpful to use jsdoc format for each configuration to provide a standard way of describing types, optionality, default values, etc.: http://usejsdoc.org/tags-param.html

**Comment by alump** [comment]
I think I already saw improvement to this documentation @Toshegg @limonte - right?

**Comment by limonte** [comment]
> I think I already saw improvement to this documentation @Toshegg @limonte - right?

There are improvements, but we are not finished with this task yet.
