### ISSUE TITLE
Add documentation for the `filters` property

### ISSUE THREAD

**Issue by davidrleonard** [vaadin/px-data-grid#378]
Please document:

* What configurations are available for each filter object (see #374 for format), including whether the config is optional or required, what type is expected, and what the default is if any
* What are the different `action` that can be passed? What does each one do?
* What are the different `column.type` that can be passed? You give examples for string, date, and number, are there more available? If more are available, document the syntax for using those types.
* Do I need to create a `columns` array and pass `type` for each column to use this? Or will the grid infer the column type if none is provided? Or am I just getting the column manually by path in the`column.path`, and using `column.type` to describe its type?

**Comment by alump** [comment]
Filters changed now because of Q1 changes, so this is actually Q1 bug now.

@Toshegg do this when other things starts to be ready
