### ISSUE TITLE
Value `0` in `tableData` is not rendered by the grid

### ISSUE THREAD

**Issue by davidrleonard** [vaadin/px-data-grid#379]
### Steps to reproduce

1. Create a px-data-grid tag 
2. Pass in the following `tableData`:

```
[
  { name: 'Apples', count: 1 },
  { name: 'Oranges', count: 0 },
  { name: 'Grapes', count: 2 }
]
```

**Expected behavior:** In the row for Oranges, the count cell be rendered as "0"
**Actual behavior:** In the row for Oranges, the count cell is empty

### Version

px-data-grid: v1.1.0
Browsers: Chrome 64

### Reproduction

The CodePens below shows a minimal reproduction: https://codepen.io/davidleonard/pen/dJgxXj

### Screenshot

![image](https://user-images.githubusercontent.com/6456757/35061284-a65bdcda-fb75-11e7-8f44-75344e43c52e.png)

**Comment by alump** [comment]
@Toshegg some if(! check should be changed to if(... === undefined)
