### ISSUE TITLE
Replacing data does not update auto-generated columns

### ISSUE THREAD

**Issue by davidrleonard** [vaadin/px-data-grid#386]
### Steps to reproduce

1. Create a px-data-grid tag
2. Pass in some `tableData`:

```
[
  { name: 'Apples', count: 1 },
  { name: 'Oranges', count: 3 },
  { name: 'Grapes', count: 2 }
]
```

3. After the grid renders, open the console and replace the `tableData` with a new array:

```
[
  { firstName: 'John', lastName: 'Smith' },
  { firstName: 'Alice', lastName: 'Gonzales' },
  { firstName: 'Maria', lastName: 'Sueryo' }
]
```

**Expected behavior:** The new data is rendered
**Actual behavior:** The table is rendered without any data

Perhaps this is expected behavior. Do we only auto-generate columns the first time data is passed into `tableData`? If so we should document that behavior to be explicit about it, and tell developers they will need to define columns on their own if they're planning to re-use the grid with different data sources.

### Version

px-data-grid: v1.1.0
Browsers: Chrome 64

### Reproduction

The CodePens below shows a minimal reproduction: https://codepen.io/davidleonard/pen/QaJLqa

**Comment by alump** [comment]
I think this is expected behavior (we don't want to loose user's column settings if new data set has minor change). But not sure how to force grid to resolve columns by code.

**Comment by davidrleonard** [comment]
Sounds good to me just checking. We can add that to the docs for tableData property and/or columns property so the developer knows what to expect.
