### ISSUE TITLE
Only 49 items from `tableData` are rendered

### ISSUE THREAD

**Issue by davidrleonard** [vaadin/px-data-grid#388]
### Steps to reproduce

1. Create a px-data-grid tag
2. Pass in some `tableData`. It should be a large amount, try 300. Do not use remoteDataProvider, pass the data in manually to the `tableData` property all at once.

**Expected behavior:** All of the rows are rendered
**Actual behavior:** Only 49 rows are rendered, even if you scroll to the bottom of the table

It doesn't seem like setting `size` to the number of `tableData` items fixes this. Even so, the grid should still be able to render all of its items without the size being configured, correct?

### Version

px-data-grid: v1.1.0
Browsers: Chrome 64

### Reproduction

The CodePens below shows a minimal reproduction: https://codepen.io/davidleonard/pen/EoOjYe

**Comment by alump** [comment]
Ok, this._vaadinGrid.items gets defined for some reason.

**Comment by alump** [comment]
Original issue was with normal grid, this is paginated grid.

**Comment by alump** [comment]
Also tested with https://github.com/vaadin/px-data-grid/pull/621 (adds 250 row version to paginated demo page) and it worked fine.

**Comment by ppeyro** [comment]
It doesn't matter if it's paginated or a regular grid, only 50 rows render using the test file in the gist above. Here's a screenshot of the same test file with a regular grid (just remove paginated from tags and queryselector in the gist):

![screen shot 2018-02-08 at 8 52 05 am](https://user-images.githubusercontent.com/10835611/35986312-8548c8fc-0cad-11e8-9ced-b2a4c8593a0b.png)

I do see it working in regular grid in **basic examples demo**. But in paginated demo, there are only 47 rows, so not sure what paginated demo page with 250 rows you are referring to in above comment?  Here's what I see in paginated demo with V1.1.11:

![screen shot 2018-02-08 at 8 59 07 am](https://user-images.githubusercontent.com/10835611/35986620-63cd5034-0cae-11e8-9300-fcd7ff7532ef.png)

**Comment by ppeyro** [comment]
Never mind, false alarm.  Forgot to update the limit imposed in js code that's loading the grid.
