### ISSUE TITLE
Numbers not rendered in IE and FF

### ISSUE THREAD

**Issue by benoitjchevalier** [vaadin/px-data-grid#389]
"number" values are not rendered for IE and FF. works in chrome/safari. Both number and floats do not render

I made a codepen for FF but it doesn't work in IE because it's not transpiled: https://codepen.io/anon/pen/dJQoJo

version: px-data-grid: v1.1.0

**Comment by alump** [comment]
In this example type of same values change from Strings to Numbers. How should we handle case where same values are sometimes Numbers, and sometimes Strings?

**Comment by alump** [comment]
One way to handle this would just handle everything as string in this. But then any filter options that do not work with String will not work. Also ordering would behave as Strings (10 is smaller than 2). And so on.

**Comment by alump** [comment]
Replaced 1.1.0 with 1.1.7 and it's works now.
