### ISSUE TITLE
Edit buttons do not have correct styles

### ISSUE THREAD

**Issue by davidrleonard** [vaadin/px-data-grid#395]
### Steps to reproduce

1. Create a basic HTML page, import the following only:

```
  <script src="../../webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="../../polymer/polymer.html"/>
  <link rel="import" href="../../px-theme/px-theme-styles.html"/>
  <link rel="import" href="../px-data-grid.html"/>
```

Load the px-theme:

```
  <custom-style>
    <style is="custom-style" include="px-theme-styles"></style>
  </custom-style>
```

Do not load the px-demo components or styles. Just load these basic elements.

2. Create a px-data-grid tag, make it editable, and add some columns and data:

```
<px-data-grid editable></px-data-grid>
<script>
  var grid = document.querySelector('px-data-grid');

  grid.columns = [
    {
      name: 'Name',
      path: 'name',
      type: 'string',
      editable: true,
      renderer: 'px-data-grid-string-renderer'
    }
  ];

  grid.tableData = [{ name: 'John' }];
</script>
```

3. Click on the edit button to the right of the row.

**Expected behavior:** The pencil edit button should be blue when the user is not hovering over it, as it is in the demo page. When edit mode is enabled, the save/reject buttons should have circles around them and be the correct color.
**Actual behavior:** The pencil edit button is black. The save/reject buttons are black and do not have circles around them.

### Version

px-data-grid: v1.1.0
Browsers: Chrome 64

### Screenshots

1. How it looks in this basic HTML page, incorrect:

![image](https://user-images.githubusercontent.com/6456757/35073538-31963a20-fb9e-11e7-990b-5ac76516e946.png)

![image](https://user-images.githubusercontent.com/6456757/35073551-3ca930c0-fb9e-11e7-8730-ade79932b416.png)

2. How it looks in demo, which seems to match spec:

![image](https://user-images.githubusercontent.com/6456757/35073562-5471df0e-fb9e-11e7-83b6-7909977d7b9f.png)

![image](https://user-images.githubusercontent.com/6456757/35073572-5f293852-fb9e-11e7-9263-f3ad7d71cdd8.png)

**Comment by alump** [comment]
Isn't it good enough that default look'n feel is useable? As far as I know there are no requirements how these should look and behave without theming. For sure those should not be blue.

**Comment by davidrleonard** [comment]
From slack:

1. I suppose the colors will be fixed when we are ready to launch px-data-grid, and we add the px-data-grid colors to px-theme
2. Should there not at least be some indication that the edit buttons are clickable without theming? E.g. there should be a cursor:pointer rule that shows a button-style cursor on hover? I believe there is no button-style cursor on either the themed or unthemed grid, now that i look at it.
3. Shouldn't the circles still surround the save/reject edit buttons without theming? If the buttons are black without theming, then the circles can be black as well I suppose.

Adding here:

Perhaps we should just fix the cursor:pointer CSS rule for the buttons and add the circles around the save/reject buttons in unthemed as well as themed.
