### ISSUE TITLE
No way to update grid data

### ISSUE THREAD

**Issue by davidrleonard** [vaadin/px-data-grid#398]
### Steps to reproduce

1. Create a px-data-grid tag and pass in some initial `tableData`:

```
  <px-data-grid></px-data-grid>

  <script>
    const grid = document.querySelector('px-data-grid');
    grid.tableData = [
      { name: 'Apples', count: 4 },
      { name: 'Oranges', count: 3 },
      { name: 'Grapes', count: 2 }
    ];
  </script>
```

2. After the grid renders, try to update the count for apples in the console. Assume the app needs to update the count for apples because it has received an update from the server notifying it that more apples are available. The grid should now show 10 apples.

I tried to use Polymer's array mutation API to set the value but it didn't trigger a re-render:

```
grid.set('tableData.0.count', 10);
```

I also tried to mutate the `tableData` object directly, then slice it to create a new reference that triggers data binding in Polymer:

```
grid.tableData[0].count = 10;
grid.tableData = grid.tableData.slice(0);
```

The only way I could force a re-render was to mutate the `tableData` object, then map over each item inside of it and use `Object.assign` to create a new item with a copy of all of the original item's data:

```
grid.tableData[0].count = 10;
grid.tableData = grid.tableData.map(item => Object.assign({}, item));
```

It appears each item's reference is cached at some point after its corresponding row is rendered, and there is no way to force the grid to re-render that item unless you pass a reference to a completely new item. Is there some API or method I should instead to notify the grid to re-render an item or all the items? I might have missed that.

If there is not an API, I would propose that using Polymer's array/object mutation methods (`grid.set('tableData.0.count', 10);`) should trigger re-rendering. Obviously we cannot keep track of arbitrary mutations to the `tableData` items. That is OK. As long as we respond correctly to expected notifying data changes, we should be fine.

### Version

px-data-grid: v1.1.0
Browsers: Chrome 64

**Comment by alump** [comment]
@limonte - Can you check how we enable observers for single item properties (should refresh that row if shown), if this is hard to do, then maybe just some grid.refreshItem(item) method?

**Comment by Aileen-H** [comment]
PRIORITY 1

**Comment by alump** [comment]
Reopenning, I think fix to this broke more than it fixed.
