### ISSUE TITLE
Make "Group by Column" and "Expandable Rows" exclusive

### ISSUE THREAD

**Issue by vonsichart200** [vaadin/px-data-grid#401]
**Current:**
The user can engage both features at the same time

**Expected:**
The user can only activate ether "Group by Column" or "Expandable Rows"

**Comment by alump** [comment]
How we should do this, should we just make grouping disabled by default, and when it's enabled then expanding will not be allowed?

**Comment by vonsichart200** [comment]
If I rephrase your suggestion:

Use case 1:  **grouping** disabled by default, and when it's enabled then **expanding** will not be allowed
Use case 2: **expanding** is disabled by default, and when it's enabled then **grouping** will not be allowed?

**Comment by alump** [comment]
Expanding works in the way that application provides template used to expand. So should it work so that if expanding template is provided, then grouping option is not offered in UI? @vonsichart200
