### ISSUE TITLE
Column with type="number" should have min and max properties

### ISSUE THREAD

**Issue by Toshegg** [vaadin/px-data-grid#404]
As mentioned in https://github.com/vaadin/px-data-grid/pull/372 PR, user should have the ability to set bounds for px-slider.

**Comment by alump** [comment]
Fix not provided yet, reopen

**Comment by alump** [comment]
In other words: Slider to be ONLY used if min AND max are provided. Any of those two missing, then slider filtering MUST NOT be offered.
