### ISSUE TITLE
"Actions" items' style should be updated

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#409]
## Description

When you select **Actions**, notice the "export CSV" item or any other custom options added look disabled (text transparency and disabled icon rendering on hover) even though the action is clickable and completes the action as expected.
This has been present since the initial tag but didn't file it until I got a chance to check with design team.

## Version
Data-grid: V1.1.1 
Browser: Chrome63

## Screenshot
<img width="954" alt="screen shot 2018-01-18 at 9 45 41 am" src="https://user-images.githubusercontent.com/10835611/35113065-0f5a6002-fc35-11e7-9b2e-a0517ff06e71.png">

**Comment by alump** [comment]
We do not have styles for this, so no idea what to do here. Also the whole idea of using disabled options have backfired now, as px-dropdown changed it's behavior.

**Comment by alump** [comment]
Now as px-dropdown supports unselectable items I think this has been resolved.
