### ISSUE TITLE
dropdown missing options

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#410]
## Description
iron dropdown options gone missing in the latest tag.
Only "freeze Column" is available in V1.1.1, "hide column" and "group by" options are no longer there.

## Version
Data-grid: V1.1.1
Browser: Chrome

## Screenshot
![screen shot 2018-01-18 at 9 59 08 am](https://user-images.githubusercontent.com/10835611/35113450-4b158fda-fc36-11e7-8dda-78ce490fe4ac.png)

**Comment by alump** [comment]
Fixed now in master, px-dropdown behavior changed yesterday.
