### ISSUE TITLE
Action item selection broken in latest tag

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#417]
## Description

Selecting exportCSV in the actions dropdown used to work as expected despite issue #409 (in V1.1.1 and previous), it no longer works in V1.1.2. 
In basic demo (with Actions menu toggled on), data was successfully exported to Excel but with V1.1.2, it fails with no errors in console.  

## Version
Data-grid: V1.1.2
Browser: Chrome

## Screenshot
![screen shot 2018-01-18 at 1 32 13 pm](https://user-images.githubusercontent.com/10835611/35122564-0f498092-fc54-11e7-80ca-4749d94197eb.png)

**Comment by alump** [comment]
Broken by change in px-dropdown. We have no way to fix this from our side.
