### ISSUE TITLE
Document how to generate icons font and add new icons

### ISSUE THREAD

**Issue by limonte** [vaadin/px-data-grid#42]
https://github.com/vaadin/px-data-grid/blob/master/px-data-grid-theme.html#L11

This line is currently unmaintainable for other developers because it's not obvious how it was generated.

Document the process of how to add new icons.

**Comment by Toshegg** [comment]
@limonte, please check https://github.com/vaadin/px-data-grid/wiki/How-to-add-icons-to-the-custom-icon-font

**Comment by limonte** [comment]
LGTM, thanks. Let's revisit it after purchasing the Basic Plan for icomoon (waiting approval for that)

**Comment by limonte** [comment]
Done: https://github.com/vaadin/px-data-grid/wiki/How-to-change-add-icons-to-the-custom-font
