### ISSUE TITLE
Contextual Header Menu uses wrong capitalization

### ISSUE THREAD

**Issue by vonsichart200** [vaadin/px-data-grid#427]
Current:
- "By" is capitalized: "Group By Column"

Expected:
- "by" is lower case: "Group by Column"

**Comment by alump** [comment]
Ok, so just to be sure, as this was already once fixed (wrongly). Should px-data-grid perform any automated capitalization or not? If px-data-grid needs to do automatic capitalization, then we need JS library to use. If not, then there has been some misunderstanding here. And I will just remove any automated capitalization. @vonsichart200

**Comment by vonsichart200** [comment]
Yes, please remove auto capitalization. We will have to do it manually. Good luck to all of us. @alump
