### ISSUE TITLE
Hiding a grouped column should be disabled

### ISSUE THREAD

**Issue by vonsichart200** [vaadin/px-data-grid#441]
**Current:**
1. View "Basic Examples"
2. Select from contextual header menu of the "First" column: "Group by Column"
3. Select from contextual header menu of the "First" column: "Hide Column"
4. Note hot the grid shows only empty gray bars

![screen shot 2018-01-22 at 12 49 04 pm](https://user-images.githubusercontent.com/25111262/35243686-a5452d3c-ff72-11e7-90ef-5deee4a11ad7.png)

**Expected:**
The user is not able to hide a column that the table is grouped by.

**Comment by alump** [comment]
@limonte - can you add some sanity check that column that has been used to group by can not be hidden

**Comment by Aileen-H** [comment]
PRIORITY 2
