### ISSUE TITLE
IE11: Can't save the edited value in IE11(numbers only)

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#446]
## Description

If a **_number_** column is editable, editing the number works fine, but saving it doesn't seem to work in IE11 only.  It reverts back to the original value.  Same test scenario with a **_string_** column works fine(new edited value is saved and rendered as expected).

No errors in console log.

## Version
Data-grid: V1.1.4
Browser: IE11

## Screenshot
![screen shot 2018-01-22 at 4 36 12 pm](https://user-images.githubusercontent.com/10835611/35251962-dada2cfc-ff92-11e7-9cb7-98da45cf72da.png)

**Comment by alump** [comment]
I think this behaviour should happen for all browsers now. As we removed the auto change apply...

**Comment by Aileen-H** [comment]
PRIORITY 1
