### ISSUE TITLE
Should advanced filtering use restamp for templates

### ISSUE THREAD

**Issue by alump** [vaadin/px-data-grid#455]
Right now there are many hidden templates in advanced filtering. Should those dom-ifs have restamps to make it little lighter.

Low priority issue, doesn't block delivery.

**Comment by Toshegg** [comment]
@alump, polymer docs say that `restamp: true` has worse performance:
![image](https://user-images.githubusercontent.com/5630034/35336634-ab34fbe0-0121-11e8-8508-a976111e672d.png)

**Comment by alump** [comment]
It's worse if you toggle those often, but in case of advanced filtering it's quite stable. Also as we keep on adding more dom-if elements there we will soon have 10+ hidden templates for each row. I would expect this also have some performance penalty.

**Comment by alump** [comment]
Again this bug is to be done if there are not other (more important) issues open. Current implementation is just fine for now.

**Comment by Toshegg** [comment]
@alump, in the case, when selecting different column could cause changes of filter set I think performance is more important that DOM-structure's beauty. Also, `display: none` is much more productive than `document.createElement`.

**Comment by alump** [comment]
I already saw performance issues without restamp when adding header magic, so added restamps
