### ISSUE TITLE
Row height doesn't scale with editable content size

### ISSUE THREAD

**Issue by davidrleonard** [vaadin/px-data-grid#456]
### Steps to reproduce

1. Create a px-data-grid custom renderer. In the non-editing (default) state, just render value as a string. In the editing state, render an input box (or anything else) with a height larger than the non-editing state element.
2. Pass some data into px-data-grid, load the page, and hit edit for the row

**Expected behavior:** When editing mode is enabled, the row automatically scales its height to fit the new content
**Actual behavior:** The row is the wrong height and the editable element is cut off

### Discussion

This is related to #394. The issue appears to come from the same place: 

https://github.com/vaadin/px-data-grid/blob/62ea5dac512ce2b25c6e92dd9b98c277dc448e01/px-data-grid-renderer-mixin.html#L64

When editing is enabled, the height of the cell is measured before the DOM re-renders to show the editable content. The measured height is set manually on the cell. This only happens once, and the manual height isn't removed later when editing is turned off. I'm not sure why that happens - is there a reason cell needs to be a fixed static height in editing mode, but not in default mode? 

If there is a reason why we can't let the row size itself using the standard approach - just have it use CSS to size to the height of its contents - we need to find a way to ensure the measurement sets the right static value. First preference, we could not do a fixed height at all. Fallback, we could allow the renderer to define its height when editing mode is enabled (and potentially update it later).

### Version

px-data-grid: v1.1.4
Browsers: Chrome 64

### Reproduction

Running example: https://px-data-grid-bug-edit-height.glitch.me/
Code for example: https://glitch.com/edit/#!/px-data-grid-bug-edit-height?path=views/index.html:1:0

### Screenshot

![data-grid-height-screenshot](https://user-images.githubusercontent.com/6456757/35303977-bd047f32-0048-11e8-93e0-ed4a91f5c516.png)

**Comment by Aileen-H** [comment]
PRIORITY 2
