### ISSUE TITLE
Data providers should get advanced filter rules in params

### ISSUE THREAD

**Issue by alump** [vaadin/px-data-grid#458]
Right now external data-providers have no clean way to get advanced filtering rules. So make copy of rules to params given to data-providers. Data providers most not need to find reference to grid elsewhere and resolve those values from there.

If you replace params.filters, then make sure it also includes the autofiltering, and make sure the demo page for remote datasource still works with autofiltering (it really will not work with advanced with all the conditions, we need to do the limitation of offered conditions too later).

This doesn't block the delivery this week, but needs to be done right after it.

**Comment by Toshegg** [comment]
Started to dig into this issue, but I'm not sure that I understand the point correctly. Can you please either explain what the purpose of this or handle this issue yourself if you know how to do that?

**Comment by alump** [comment]
So dataproviders of px-data-grid are functions with two parameters. First is param that should include all information needed to generate data query, and then second is callback function that data provider needs to call with data.

Challenge now is that first parameter does not have these advanced filtering objects at all. It only has the filters that is only populated with auto filtering if it is used.

So task is to make sure params include the current state of filtering (including advanced filtering), so outside providers can check how data needs to be filtered.
