### ISSUE TITLE
Wrong cursor on hover for editable cells

### ISSUE THREAD

**Issue by davidrleonard** [vaadin/px-data-grid#459]
Related to #444 but focused on the cell hover cursors and color, not the pencil icon.

### Steps to reproduce

1. Create a px-data-grid and make it editable:

```
<px-data-grid editable></px-data-grid>
```

2. Pass in custom columns. Create one editable column and one non-editable column:

```
[
  { 
    name: 'Name',
    path: 'name',
    editable: false
  },
  {
    name: 'Email',
    path: 'email',
    editable: true,
    renderer: 'px-data-grid-string-renderer'
  }
]
```

3. Load the page and pass in some sample data to the grid
4. Hover over a non-editable cell in the Name column

**Expected behavior:** The cursor should remain `cursor: default` and not be set to `cursor: text`
**Actual behavior:** The cursor is set to `cursor: text`

5. Hover over an editable cell in the Email column

**Expected behavior:** The cursor should be set to `cursor: text` and the text should change to blue color (color in spec)
**Actual behavior:** The cursor changes as expected, but the text color does not change

So the issues to be fixed are:

* On non-editable cells, cursor should not change on hover
* On editable cells, text color should change to blue on hover

### Version

px-data-grid: v1.1.4
Browsers: Chrome 64

**Comment by Aileen-H** [comment]
1/24: Dependency on px design team to come back with interaction for hover/color on editing row /cell state. Vaadin can review and we can decide if doable or enhancement.

**Comment by Aileen-H** [comment]
PRIORITY 3

**Comment by alump** [comment]
@Aileen-H  Closing this soon if no update from design team.

**Comment by vonsichart200** [comment]
On it.

**Comment by vonsichart200** [comment]
Verified with Padi and David. This issue is OK to close.

**Comment by alump** [comment]
Thanks.
