### ISSUE TITLE
Removed/edited cell contents seem to remain filterable

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#462]
## Description

When a cell content is edited, auto filter returns the row based on the old content. Somehow the old state/value is retained?  See screenshots below in sequence:

Steps to Repro on the demo:
1. Go to custom demos
2. select editable and auto filter
3. Change a first name to something new, then save.
4. In autofilter, search for the "old" content. 
Note the filter returns the edited row with the new content

## Version
Data-grid: V1.1.4

## Screenshots
![screen shot 2018-01-23 at 4 04 26 pm](https://user-images.githubusercontent.com/10835611/35307903-06099648-005a-11e8-917a-501ecc5a8f0c.png)

![screen shot 2018-01-23 at 4 04 45 pm](https://user-images.githubusercontent.com/10835611/35307941-1185ca00-005a-11e8-9d96-dfd1254249c7.png)

![screen shot 2018-01-23 at 4 07 16 pm](https://user-images.githubusercontent.com/10835611/35307943-16cedb0a-005a-11e8-85d5-6b998ebb6ddc.png)

**Comment by Aileen-H** [comment]
PRIORITY 1

**Comment by toshegg** [comment]
The first happens because of hidden 'Full name' column, which still contains 'Elizabeth Wong', that's why it appears in search results.

Can't reproduce the second:
![image](https://user-images.githubusercontent.com/5630034/35912031-21a46634-0c04-11e8-8fc4-23998df52407.png)
Please, attach a screenshot of filters that you are applying.

**Comment by alump** [comment]
Of course... I should have noticed that as I added that generared hidden column there to test things.

**Comment by ppeyro** [comment]
My bad, completely missed the hidden column!  
Retested and it certainly works fine returning the expected filtered row after any edits.
