### ISSUE TITLE
Error detection for editable columns

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#463]
## Description

The spec (page 72) specifies simple error detection when cells are edited with unexpected content, e.g. string in a number column. 
Was not able to trigger an error in a "number only" column when entering a string.  The invalid string value was successfully saved in the column and rendered as a NaN after save.

Unclear if the error detection was implemented or backlogged?  
Filing this for tracking purposes.

## Version
Datagrid: V1.1.4

## Screenshot
![screen shot 2018-01-23 at 5 20 02 pm](https://user-images.githubusercontent.com/10835611/35309540-d98c724a-0061-11e8-849a-080963157856.png)

**Comment by alump** [comment]
@Toshegg - can you add NaN check to number editor validation? thanks.
