### ISSUE TITLE
"Export CSV" option in Actions dropdown should not be selectable, just clickable

### ISSUE THREAD

**Issue by talimarcus** [vaadin/px-data-grid#465]
### Steps to reproduce
1. Click "Actions" dropdown
2. Click "Export CSV" option

**Expected behavior:** Click triggers CSV download, but does **not** select the "Export CSV" option
**Actual behavior:** Click triggers CSV download, and selects the "Export CSV" option

### Version
px-data-grid: v1.1.4
Browsers: Chrome 64, Firefox 57, Safari 11

### Screenshot
![screen shot 2018-01-23 at 4 53 02 pm](https://user-images.githubusercontent.com/9092541/35313953-0392e202-0078-11e8-8043-76b3d401ae27.png)

**Comment by alump** [comment]
Sounds like you are using old version of px-dropdown, please remove bower_components and re-run bower install. @talimarcus

**Comment by alump** [comment]
Closing as works-for-me. Also tested fresh version with fresh bower_components folder, and still worked, so px-dropdown hasn't been broken.
