### ISSUE TITLE
Cannot sort by column header using the keyboard

### ISSUE THREAD

**Issue by talimarcus** [vaadin/px-data-grid#466]
### Steps to reproduce
1. Use keyboard to navigate to the table header
2. Use arrow keys to navigate to the column you would like to sort
3. Press "Enter" key

**Expected behavior:** Rows are sorted according to the selected column, as they would be if you clicked the column header with a mouse. 
**Actual behavior:** Nothing happens and the focus ring disappears, but focus remains on the item.

### Version
px-data-grid: v1.1.4
Browsers: Chrome 64, Firefox 57, Safari 11

**Comment by alump** [comment]
We can check if this is easy to implement now.

**Comment by limonte** [comment]
This issue is fixed, but the toggling of column sorting works with Space, not with Enter.

To clarify the difference:

- Enter generates the focus event for the first child
- Space generates the click event for the first child
