### ISSUE TITLE
Keyboard navigation does not move left to right in "Remote data provider" demo

### ISSUE THREAD

**Issue by talimarcus** [vaadin/px-data-grid#470]
### Steps to reproduce
1. Go to the "Remote data provider" demo
2. Tab to the first row of data in the data-grid
3. Use the right arrow to navigate through the data in row one

**Expected behavior:** Focus moves from left to right, one column at a time without skipping over any items
**Actual behavior:** Focus moves from column 0 ("Index") to column 9 ("Address"), then proceeds left to right when it wraps around to column 1 ("Name")

### Version
px-data-grid: v1.1.4
Browsers: Chrome 64, Firefox 57, Safari 11

**Comment by limonte** [comment]
This is the vaadin-grid issue, reported https://github.com/vaadin/vaadin-grid/issues/1193

**Comment by Aileen-H** [comment]
Priority 2

**Comment by limonte** [comment]
Fixed, please update Bower dependencies before testing.
