### ISSUE TITLE
Pagination feature is not keyboard accessible

### ISSUE THREAD

**Issue by talimarcus** [vaadin/px-data-grid#471]
### Steps to reproduce
1. To go the "Pagination" demo
2. Try to tab to the pagination

**Expected behavior:** User should be able to navigate through the pagination numbers with the arrow keys and see what number currently has focus. User should be able to select a page number using the Enter key.
**Actual behavior:** Pagination controls don't get focus at all.

### Version
px-data-grid: v1.1.4
Browsers: Chrome 64, Firefox 57, Safari 11

**Comment by alump** [comment]
@drewharvey check keyboard navigation of navigation UI

**Comment by alump** [comment]
@limonte - If you work with other keyboard navigation issues, and would like to fix this, feel free to steal it. Drew will be busy with other tasks now anyway.

**Comment by alump** [comment]
@limonte can you take this, thanks.
