### ISSUE TITLE
Tabbing from header to first row scrolls the data in the grid

### ISSUE THREAD

**Issue by talimarcus** [vaadin/px-data-grid#472]
### Steps to reproduce
1. Tab from data-grid header to first row of data-grid

**Expected behavior:** Data does not scroll when tabbing between header and data
**Actual behavior:** The table automatically scrolls down and hides most of the first item.

### Discussion
Note: this does not happen on the other scrollable examples

### Version
px-data-grid: v1.1.4
Browsers: Chrome 64, Firefox 57, Safari 11

### Screenshot
![screen shot 2018-01-23 at 5 04 24 pm](https://user-images.githubusercontent.com/9092541/35315300-88f93560-0080-11e8-89e4-fc2707472c23.png)

**Comment by alump** [comment]
@limonte - please have a look at this, this might be a bigger issue

**Comment by limonte** [comment]
Depends on https://github.com/vaadin/vaadin-grid/issues/1199

**Comment by Aileen-H** [comment]
PRIORITY 2

**Comment by limonte** [comment]
Fixed, please update Bower dependencies before testing.
