### ISSUE TITLE
Expandable rows feature is not keyboard accessible

### ISSUE THREAD

**Issue by talimarcus** [vaadin/px-data-grid#473]
### Steps to reproduce
1. Go to the "Expandable Rows" demo
2. Tab focus to the expand arrow of one of the rows & press Enter

**Expected behavior:** The item will expand as it does when you click the arrow with a mouse
**Actual behavior:** Nothing happens and the focus ring disappears.

### Version
px-data-grid: v1.1.4
Browsers: Chrome 64, Firefox 57, Safari 11

### Screenshot
<img width="1011" alt="screen shot 2018-01-23 at 9 06 53 pm" src="https://user-images.githubusercontent.com/9092541/35315468-65823ebe-0081-11e8-97e6-6c65e795a78d.png">

**Comment by limonte** [comment]
This issue is fixed, but the toggling works with Space, not with Enter.

To clarify the difference:

- Enter generates the `focus` event for the first child
- Space generates the `click` event for the first child
