### ISSUE TITLE
Inline editing feature is not keyboard accessible

### ISSUE THREAD

**Issue by talimarcus** [vaadin/px-data-grid#474]
### Steps to reproduce
1. Enable the editable feature
2. Use the keyboard to navigate to the editing icon & press Enter

**Expected behavior:** The row becomes editable as it does when you click the editing icon with the mouse.
**Actual behavior:** Nothing happens and the focus ring disappears

### Discussion
Navigating to the editing icon and pressing Enter should make the current row editable. Then the user should be able to navigate between columns with the arrow keys. When the user navigates to an editable item and presses Enter, that item should be editable using the keyboard. E.g. if the user navigates into the "Age" column, presses enter, then uses the up/down arrow keys, the arrows will change the content in Age rather than navigate through the cells. If the user presses Enter again, the item will no longer be in "editing mode" and using the up/down arrow keys will navigate between rows. 
The user should also be able the navigate between the check mark and X icons with the arrow keys. 
Note: this should be discussed further with the designers.

### Version
px-data-grid: v1.1.4
Browsers: Chrome 64, Firefox 57, Safari 11

**Comment by alump** [comment]
@Toshegg - We are using px-icons in edit buttons, was there reason why we didn't use button with icon here? Button would probably handle keyboard navigation better without need to make px-icons behave like buttons.

**Comment by toshegg** [comment]
@alump, yes, that should fix the issue. Can you please include this in your PR https://github.com/vaadin/px-data-grid/pull/525 ? 
The reason why I'm asking is that you have an issue there with disappearing icons, so you can change icons to buttons simultaneously.

**Comment by Aileen-H** [comment]
PRIORITY 1

**Comment by alump** [comment]
I need to move each action button to own cell (and so own column) to fix this.

**Comment by limonte** [comment]
I submitted 2 PRs to px-datetime-field and px-datetime-picker:

- https://github.com/PredixDev/px-datetime-field/pull/8
- https://github.com/PredixDev/px-datetime-picker/pull/33

**Comment by limonte** [comment]
> PredixDev/px-datetime-field#8
> PredixDev/px-datetime-picker#33

merged, released.
