### ISSUE TITLE
Sorting a column when in groupby should not collapse the expanded view.

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#479]
## Description

When groupby mode is expanded, sorting the grid on a different column would cause the expanded view to collapse first.

## Version
data-grid:1.1.5
Browser: Chrome

### Initial expanded view
![screen shot 2018-01-24 at 12 51 54 pm](https://user-images.githubusercontent.com/10835611/35357312-fb6e982e-0107-11e8-90a9-df507a58fefa.png)

### After sorting the expanded view
![screen shot 2018-01-24 at 12 52 21 pm](https://user-images.githubusercontent.com/10835611/35357324-05791b5a-0108-11e8-8d0c-b74b8e91d0bf.png)

**Comment by alump** [comment]
@limonte can you have look at that, I still don't understand the way this is done to fix it.

And as side note, if you group the basic demo by last name, and then expand Wongs. Now if you check expandedItems in vaadinGrid it shows two wong items (just lastname defined). Who this works?

**Comment by Aileen-H** [comment]
PRIORITY 2
