### ISSUE TITLE
Advanced Filtering: Truncation should be applied to filter strings longer than 15 chars.

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#483]
## Description

Per Spec, truncation should trigger for filter chips that contain more than 15 chars. It doesn't look like that's being triggered currently.

## Version
Data-grid: V1.1.5

## Screenshot
![screen shot 2018-01-24 at 1 45 59 pm](https://user-images.githubusercontent.com/10835611/35358946-35d9c3b2-010d-11e8-94c4-fa816b8afabc.png)

**Comment by alump** [comment]
@ppeyro Just to fix this correctly, what truncation we should use here?

**Comment by ppeyro** [comment]
I believe there is a guideline for truncation. I'll ask the design team to update the issue with specifics.

**Comment by andrealperry** [comment]
Please see guidance for truncation in the writing guidelines (scroll to the bottom of the table): https://www.predix-ui.com/#/design/writing

**Comment by alump** [comment]
@andrealperry it shows both middle and end. Should be use middle or end? If end we could also just have it done by defining the width of chip. But in case of middle we need to do it with JS (you had a behaviour or something we could use here?)
