### ISSUE TITLE
Advanced Filtering:  Overflow hover not triggered when multiple filters applied

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#491]
## Description

When multiple filters are applied, hovering over the filter chip should trigger a tooltip listing all the applied filters per spec.  Not happening in this version.

## Version
Datagrid: V 1.1.5
Browser: FF58, Chrome, IE11, Safari10

## Screenshot

![screen shot 2018-01-24 at 6 31 14 pm](https://user-images.githubusercontent.com/10835611/35367775-03e76648-0135-11e8-8d6e-9ffb76bf55cd.png)

**Comment by alump** [comment]
@ppeyro is this firefox only, or all browsers?

**Comment by alump** [comment]
@Toshegg High priority issue

**Comment by ppeyro** [comment]
Update the browser list. It's on all of them so far.

**Comment by alump** [comment]
We can not use px-tooltip here, px-popover is used here because you can not move your cursor to tooltip. So you need to click it. If you can tell us how to make px-tooltip work here, we can convert to it, but we haven't way to use it. @ppeyro

**Comment by alump** [comment]
Designers are investigating this. We could make auto-close disabled with tooltip, but then we need clear rules when it's closed. Also I think px-tooltip should offer all this functionality.

**Comment by alump** [comment]
Closing soon as wontfix, if no feedback. @ppeyro

**Comment by ppeyro** [comment]
Please leave this issue open for now. I will ask Aileen to prioritize this with the design team to look into/answer.

**Comment by benoitjchevalier** [comment]
This can be done with px-tooltip by using the `for` property and enabling `ignoreTargetEvents`. You then manually open/close the tooltip through the `opened` property. 

Still need to decide on interaction to have the tooltip on/off though (assuming 'on' on click and off on timer or outside click. Designers will have to weigh in)

**Comment by ppeyro** [comment]
@alump Based on the latest discussions, the design team has decided to optimize this interaction and remove the hover state from what was originally spec'd.  So as of now, there is no longer any hover interactions required.  The interaction is limited to "select", which would trigger the modal to open, i.e. "click on multi-filter chip", modal opens. Design spec to be updated.

**Comment by Aileen-H** [comment]
1/30: Decided to not have popover or tooltip instead when you click on the "overflow" chip, the modal containing the advanced filters should appear.

**Comment by Aileen-H** [comment]
This can be closed and change implemented.

**Comment by alump** [comment]
Fix here is to remove the current "tooltip" from merge chip, and just make clicking it open advanced filter dialog.
