### ISSUE TITLE
Advanced Filtering: Overflow hover Popover inconsistencies across browsers

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#499]
## Description

Overflow hover popover has browser specific inconsistencies, in alignment as well as console errors:
- Popover has alignment issues (in the demo at least), in Chrome, Safari10, IE11.
- It also generates an error in Safari10, and IE11 in the console log)not in Chrome. I
- In FF58, it also doesn't seem to work consistently at all, but no errors in console log either.

These are reproducible with the demo file.

## Version
Data-grid: V1.1.5
Browsers: Safari10, IE11, FF58

### Alignment Issue shown in Chrome, but also present in IE11 and Safari10
![screen shot 2018-01-25 at 9 02 09 am](https://user-images.githubusercontent.com/10835611/35403577-fd1c0208-01b4-11e8-807a-7e7a60cc9450.png)

### Safari10 Console Error
![screen shot 2018-01-25 at 9 35 14 am](https://user-images.githubusercontent.com/10835611/35403340-3e19c304-01b4-11e8-91de-8b506c261b59.png)

### IE11 Console Error
![2018-01-25_0938](https://user-images.githubusercontent.com/10835611/35403376-5913ecb6-01b4-11e8-95d6-d29690bd25e8.png)

**Comment by alump** [comment]
@Toshegg Some polyfill issue or something else is wrong here. Not sure what, but please check. Thanks.

**Comment by toshegg** [comment]
There is an issue already about popover cutting: https://github.com/vaadin/px-data-grid/issues/362
I have responded there.
