### ISSUE TITLE
1.4 Column pinning (freeze)

### ISSUE THREAD

**Issue by limonte** [vaadin/px-data-grid#5]
Depends on https://github.com/vaadin/px-data-grid/issues/4

Click on `Pin column` sets the `frozen` property of corresponding `vaadin-grid-column` to `true`

For pinned column: 
 - `Pin column` menu item in the dropdown menu should be hidden
 - `Unpin column` menu item should be shown

Click on `Unpin column` sets the `frozen` property of corresponding `vaadin-grid-column` to `false`

### UI specs

![image](https://user-images.githubusercontent.com/6059356/32549116-e798bcfc-c490-11e7-9a9e-4c94c8613095.png)

![image](https://user-images.githubusercontent.com/6059356/32549121-efb136e4-c490-11e7-8109-071079ba05d5.png)

![image](https://user-images.githubusercontent.com/6059356/32549132-f9c95378-c490-11e7-984b-31fb52c89851.png)

**Comment by limonte** [comment]
As discussed in Slack, in case when user freeze a column in the middle, all columns left to it should be freezed.

**Comment by alump** [comment]
This is still open, moved to delivery 2.

**Comment by limonte** [comment]
> As discussed in Slack, in case when user freeze a column in the middle, all columns left to it should be freezed.

This is wrong, let's discuss freezing one more time in the upcoming daily.
