### ISSUE TITLE
Column dropdown for latest column should be opened to the opposite side

### ISSUE THREAD

**Issue by limonte** [vaadin/px-data-grid#50]
Actual: 

![](https://i.imgur.com/SoKlPzS.png)

Expected:

![](https://i.imgur.com/wnauInn.png)

**Comment by alump** [comment]
Verify this behavior after dropdown is moved to left.

**Comment by limonte** [comment]
Not relevant after moving three-dots icon to the left https://github.com/vaadin/px-data-grid/issues/78
