### ISSUE TITLE
Advanced Filtering: Zero State Styles should be updated

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#500]
## Description

Zero State modal styles should be updated and some elements should be removed to match the spec. 

Side by side spec+code attached below.

## Version
Data-grid: V1.1.5
Reference: Version 3 of Advanced Filtering Spec, Page 7.

## Screenshot
![screen shot 2018-01-25 at 10 22 25 am](https://user-images.githubusercontent.com/10835611/35405179-3a2f6176-01ba-11e8-86d8-aa231790aef1.png)

**Comment by alump** [comment]
Valid requests.

Btw, I think save checkbox should be made optional. As not all application will have filter saving. But that's different improvements to do.
