### ISSUE TITLE
Advanced Filtering: Tooltip content should be updated when "Any column" is selected.

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#501]
## Description

When hovering over the filter chip, the tooltip content should contain the selected filter criteria, which it does per spec and works fine in most cases.  Only exception is when "Any column" is selected as a criteria. 
For example, if you select "Any column", "equals to" "2" as your filter when you hover over the filter chip, the tooltip will contain "**Show all/Any/Equals to**" which is odd.  for Any column, the tooltip should probably contain **"Show all/Any column/equals to**"?

## Version
Data grid: V1.1.5

## Screenshots
![screen shot 2018-01-25 at 10 54 06 am](https://user-images.githubusercontent.com/10835611/35406631-5349c15c-01be-11e8-8eb6-f55d298b9444.png)

### This is the case with show Any/Any column:
![screen shot 2018-01-25 at 11 09 20 am](https://user-images.githubusercontent.com/10835611/35407298-588a2286-01c0-11e8-8b3a-d78b66cd0775.png)

**Comment by alump** [comment]
@Toshegg - just make sure same strings are used in tooltips and dialog. And dialog has the correct strings.
