### ISSUE TITLE
Advanced Filtering: Minor styling discrepancies in Modal (Zero State/Text)

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#502]
## Description

Couple of discrepancies in styling/text between spec and implementation. Listing them here for tracking/fixing:
1. Save this filter set: Currently all upper case in modal, should be lower case.
2. Attribute/condition/value headers are currently all upper case in code, spec shows them in both upper/lower case. Probably a spec issue? but might need to change it once the spec is updated. 
3. The delete filter/"X" and + Add Filter should both get the color treatment per spec, I think that might be $primaryblue, but will need confirmation from design.
4. The px-nav close icon spacing and height should match the spec.

Also in zero state, there are a couple of discrepancies:
1. Text should be changed to You have no filters
2. Reset button should be removed.

## Version
Data-grid: V1.1.5

## Screenshots:

![screen shot 2018-01-25 at 11 18 49 am](https://user-images.githubusercontent.com/10835611/35408109-ca2d51f4-01c2-11e8-9d1a-20bc6185edee.png)

![screen shot 2018-01-25 at 11 25 14 am](https://user-images.githubusercontent.com/10835611/35408192-1a7b6dbc-01c3-11e8-9528-6427e862e562.png)

### Item 3 & 4 listed above
![screen shot 2018-01-25 at 1 14 12 pm](https://user-images.githubusercontent.com/10835611/35412816-54009d6e-01d2-11e8-8cc8-d841b812b1e5.png)

**Comment by alump** [comment]
@Toshegg - These are "easy" look'n feel issues to fix.
