### ISSUE TITLE
Editing table row issue - rightmost column/cell value disappears on edit

### ISSUE THREAD

**Issue by Aileen-H** [vaadin/px-data-grid#506]
When I edit the top town on the table the last visible columen cell value disappears. Using Chrome browser in demo "Custom columns"

![screen shot 2018-01-25 at 1 53 17 pm](https://user-images.githubusercontent.com/21231643/35414433-4f32530e-01d7-11e8-932b-a541be0976fa.png)

**Comment by alump** [comment]
Needs for information, can not reproduce.

**Comment by alump** [comment]
@Aileen-H try these steps on your setup:
- Make sure to remove ```bower_components``` folder under the project
- Run ```bower install```
- Restart demo
- Repeat steps

If issue happens on installation elsewhere, force clear your browser cache. And re-try.

**Comment by alump** [comment]
Depending on https://github.com/PredixDev/px-datetime-common/issues/18
