### ISSUE TITLE
Contextual header menu has wrong font size

### ISSUE THREAD

**Issue by vonsichart200** [vaadin/px-data-grid#507]
**Current:**
Text is about 12px (Zeta)

**Expected:**
Text is about 15 pixel (Regular)

![screen shot 2018-01-25 at 2 38 08 pm](https://user-images.githubusercontent.com/25111262/35416294-7e91c2aa-01dd-11e8-88ea-291423a52a0a.png)

**Comment by alump** [comment]
Fixed by setting size to ```1rem```.
