### ISSUE TITLE
Advanced Filtering:  Wildcard filtering returns unpredictable results

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#512]
## Description

Tried to use a wildcard to filter out rows.  Specifically, a*  as the value to filter the first name column, expecting it to return all first names that start with an "a".

Getting random rows returned every time I apply it.
reproducible on the custom-column demo.

## Version
Data-grid: V1.1.5
Browser: Chrome

## Screenshots

![screen shot 2018-01-25 at 6 46 36 pm](https://user-images.githubusercontent.com/10835611/35423013-7c98a310-0200-11e8-84b9-87d20a0498fb.png)

![screen shot 2018-01-25 at 6 46 56 pm](https://user-images.githubusercontent.com/10835611/35423029-8ea69f8a-0200-11e8-91bd-a6a2853d062c.png)

**Comment by alump** [comment]
Started PR https://github.com/vaadin/px-data-grid/pull/511 - please make sure tests will pass.
