### ISSUE TITLE
Advanced Filtering: Dropdown menus are too short

### ISSUE THREAD

**Issue by vonsichart200** [vaadin/px-data-grid#523]
Current:
Menus have text length

Expected:
Menus fill the three column grid column width

![screen shot 2018-01-26 at 12 31 56 pm](https://user-images.githubusercontent.com/25111262/35459460-2211eed4-0295-11e8-84fb-671c71628ee7.png)

**Comment by alump** [comment]
Browser and server? This does not happen on our side.

**Comment by vonsichart200** [comment]
**px-data-grid v1.1.5**

Chrome - Version 64.0.3282.119 (Official Build) (64-bit)
Safari - Version 11.0.3 (11604.5.6.1.1)

**Comment by alump** [comment]
None of those answered to server where you run the app.

**Comment by ppeyro** [comment]
This seems to be happening on the deployed version. 
It's definitely not happening in my local version of the grid.  

See it in action here:
https://px-data-grid-testing.netlify.com/px-data-grid

**Comment by Aileen-H** [comment]
This can be closed.
