### ISSUE TITLE
Advanced Filtering: Apply button is not "Call to Action" style

### ISSUE THREAD

**Issue by vonsichart200** [vaadin/px-data-grid#524]
Current:
"Apply" button is grey

Expected:
"Apply" button is blue

![screen shot 2018-01-26 at 12 31 56 pm](https://user-images.githubusercontent.com/25111262/35459519-54014c6e-0295-11e8-9111-d0888ebc86aa.png)

**Comment by alump** [comment]
We got another bug asking to make it primary, it's now primary. And your primary is blue.

**Comment by alump** [comment]
This will be the very last time we will change the style of this button.

**Comment by alump** [comment]
So... in picture it's gray (not sure why). But in today's version it should have been primary blue. But I'm changing it again to call to action blue.
