### ISSUE TITLE
Advanced Filtering: Remove row "X" should make use of "px-actionable-design"

### ISSUE THREAD

**Issue by vonsichart200** [vaadin/px-data-grid#529]
See component here:
https://www.predix-ui.com/#/css/visual/px-actionable-design

Please note sizing, hover and pressed states.

![screen shot 2018-01-26 at 12 31 56 pm](https://user-images.githubusercontent.com/25111262/35464895-694b51f6-02ad-11e8-895d-17cbd3470e82.png)

**Comment by alump** [comment]
This will cause issues with keyboard navigation, I can already see it.
