### ISSUE TITLE
Improve documentation to mention default-column-flex with default-column-width

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#530]
## Description

Added the "default-column-width" in a very simple grid to change the column width to narrow columns.  Doesn't seem to work.  The columns remain at the default width.
It seems to work if you increase the width to a larger value than the default, but can't decrease it?

## Version
Data Grid: V1.1.6

## Screenshot

![screen shot 2018-01-26 at 4 42 02 pm](https://user-images.githubusercontent.com/10835611/35466398-59335092-02b8-11e8-855b-8b6ebc85a113.png)

## Code
```
<div style="height:550px; width:1200px">
  <h2>Simplest datagrid with no select and narrow columns</h2>
    <px-data-grid
      table-data='[
        {"first":"Elizabeth","last":"Wong","email":"sika@iknulber.cl"},
        {"first":"Jeffrey","last":"Wong","email":"cofok@rac.be"},
        {"first":"Alma","last":"Martin","email":"dotta@behtam.la"},
        {"first":"Elizabeth","last":"Saunders","email":"seh@bibapu.gy"},
        {"first":"Willie","last":"Dennis","email":"izko@dahokwej.ci"}
        ]'
      selection-mode="none"
      default-column-width="50px"
      >
    </px-data-grid>
  </div>

**Comment by alump** [comment]
Make window smaller and those will stop getting smaller at 50px? So it is actually using 50px as default width, but then shared unused space between all columns.

**Comment by alump** [comment]
You do not have use default-column-flex="0" defined. The default flex is 1, with width 50px those will become min 50min width. I assume the actual bug here is in documentation. The default-column-width should mention default-column-flex too?

**Comment by ppeyro** [comment]
Great.  Yes, adding the column flex did the trick, thanks Sami.  
I would not have thought of that unless you told me, so I think it's worth mentioning in the doc.

## Screenshot 
### 50px width with default-column-flex="0"

![screen shot 2018-01-29 at 10 04 25 am](https://user-images.githubusercontent.com/10835611/35526308-da654d44-04db-11e8-82aa-6d8e7f940279.png)

**Comment by Aileen-H** [comment]
PRIORITY 2
