### ISSUE TITLE
Horizontal scrollbar should not extend under frozen column

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#531]
## Description

Minor visual discrepancy: In spec, the horizontal scrollbar is not extended under the frozen column. In the implementation, the horizontal scrollbar extends the width of the whole grid, not just the "unfrozen" columns.

## Version
Data-grid: V1.1.6

## Screenshot
![screen shot 2018-01-26 at 6 16 22 pm](https://user-images.githubusercontent.com/10835611/35467654-1f4f4b20-02c6-11e8-8721-a65acdd5800b.png)

**Comment by alump** [comment]
Will not be done anymore. Scrollbars match the scroll are, and that is actual scroll area.
