### ISSUE TITLE
Advanced Filtering: Ability to disable headers in subsequent filters when columns are the same

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#536]
## Description

Advanced Filtering should provide a customizable attribute to disable headers when additional filters are specified when all columns are the same, avoiding duplication of headers for each filter defined, e.g. Attribute/Condition/Value.  This is in spec (version 4 page 11), but not implemented as of V1.1.6 yet.

## Version
Data-grid: V1.1.6

## Screenshot

![screen shot 2018-01-29 at 9 19 55 am](https://user-images.githubusercontent.com/10835611/35524165-9d2c6b34-04d5-11e8-90d1-aa5d7ed0fd21.png)

**Comment by vonsichart200** [comment]
Design suggestion is already present in "px-data-grid_filtering_v1-5_ap.pdf" published Dec, 15, 2017

**Comment by alump** [comment]
Yes, we haven't done this as it is depending on other details (like date range filtering, that has been changing).

**Comment by alump** [comment]
Added compact-advanced-filter-dialog attribute in my PR, the logic when header are hidden is little limited, but it's there. This is really bad UX as things jump all around when this is enabled, and then you add new rule to column that does not match others. Also any date filter will prevent header sharing ALWAYS.
