### ISSUE TITLE
Advanced Filtering: Minor cosmetic bug in Safari10 only

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#542]
## Description
Filter chip placement causes the box border to be clipped at the bottom.
This is both in the demo as well as test files.

## Version
Data-grid: V1.1.6
Browser: Safari 10

## Screenshot
![screen shot 2018-01-30 at 12 45 24 pm](https://user-images.githubusercontent.com/10835611/35590359-8497b768-05bb-11e8-94d4-6649723355a3.png)

**Comment by alump** [comment]
I made simple fix. Looks like chips are sized so that border is excluded in size, causing the bottom border to clip outside. So adding 1px padding to top and bottom resolves it.
