### ISSUE TITLE
Group By:  group by doesn't seem to work on filtered results

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#548]
## Description

If you have a filtered set of results based on one column and try to "group by" another columns ( other than the col used in the filter condition), you'll get an empty grid in return. This is reproducible in test files and also the basic demo, example:

1. Go to demo/basic examples/more rows
2. Setup a filter to return rows with "os" in **last** name
3. With the returned 3 rows, try to **group by** in either "**first**" or "**email**" column.
4. Note the grid returns empty rows
5. If however, you try to group by "**last**" which was also the condition ofthe filter, it will show the correct groups/rows

Additional Note:
If you use "any column" in your filter conditions, it does group by any column successfully.

## Version
Data-grid: V1.1.6

### Any column in filter
![screen shot 2018-01-30 at 4 23 40 pm](https://user-images.githubusercontent.com/10835611/35598809-4dff52aa-05da-11e8-9955-6027aa936a0c.png)

### Result: Able to "group by" on any column
![screen shot 2018-01-30 at 4 26 06 pm](https://user-images.githubusercontent.com/10835611/35598828-6873dd0e-05da-11e8-81a6-d75969bcb051.png)

### Select a specific column in filter
![screen shot 2018-01-30 at 4 24 01 pm](https://user-images.githubusercontent.com/10835611/35598924-0fc1641e-05db-11e8-9ff3-82f06e06bcd7.png)

### Result: Empty Grid after group by on "first" column
![screen shot 2018-01-30 at 4 34 07 pm](https://user-images.githubusercontent.com/10835611/35598997-7c9bb88c-05db-11e8-87a0-98d08291f752.png)

**Comment by Aileen-H** [comment]
PRIORITY 2

**Comment by alump** [comment]
Please retest with 1.2.4

**Comment by ppeyro** [comment]
@alump Rechecked this behavior in V1.2.4 and the same thing is still happening.
