### ISSUE TITLE
Contextual menu transparent on hover over header

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#553]
## Description

On hover over the header, the menu icon doesn't appear because it's transparent.
This started happening in V1.1.7, so possibly theming changes may have affected it.  Functionality of the menu is still intact though, if you click in that general area

## Version
Data-grid: V1.1.7
Browser: Chrome

## Screenshot
![screen shot 2018-01-31 at 1 54 48 pm](https://user-images.githubusercontent.com/10835611/35649605-7eeb99d2-068e-11e8-95a9-d766424934b5.png)

**Comment by alump** [comment]
Regression, we broke the unthemed version.

**Comment by ppeyro** [comment]
Looks like there is no default color when unthemed.  If we add:
<link rel="import" href="css/px-data-grid-light-theme-styles.html">

    <custom-style id="px-data-grid-theme-styles">
      <style include="px-data-grid-light-theme-styles" is="custom-style"></style>
    </custom-style>

to the test file, the transparency issue gets resolved.
