### ISSUE TITLE
Advanced Filtering: Icon on Table Filters button misaligned

### ISSUE THREAD

**Issue by andrealperry** [vaadin/px-data-grid#558]
The filters icon on the table filters button is misaligned.

Current:
![screen shot 2018-01-31 at 4 27 52 pm](https://user-images.githubusercontent.com/30873778/35655153-3b59b444-06a5-11e8-8327-54bca82ca609.png)

Expected:
![screen shot 2018-01-31 at 4 36 31 pm](https://user-images.githubusercontent.com/30873778/35655160-4c1ea2a8-06a5-11e8-9e5b-19f072d92e3e.png)

**Comment by alump** [comment]
I will reuse the same padding as the dropdown next to it has, that's rem value, not pixels. And align icon with -3px margin (it's larger than text in buttons).
