### ISSUE TITLE
Vertical separator line stays locked to the first frozen column instead of the last frozen column.

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#586]
## Description
Placement of the separator line that gets triggered when columns are frozen locks to the first frozen column instead of the last frozen column.  This used to work in previous tags, (V1.1.6)

Steps:
With the resulting grid in code below(gist link added): 

- Freeze 3 columns 
- Now scroll to the right, notice the grey separator line stays locked to the first frozen column rather than the last frozen column(column 3) as you scroll to view the rest of the columns.  The frozen columns stay locked in place as expected, just the grey line is to wrong frozen column.

## Version
Data-grid: V1.1.10

## Screenshot
![screen shot 2018-02-02 at 5 00 39 pm](https://user-images.githubusercontent.com/10835611/35761363-75da6936-083c-11e8-8ec4-03208d22a16d.png)

## Code

https://gist.github.com/ppeyro/ed78396064a017c36badc164f26688b1

**Comment by alump** [comment]
@limonte - is our last frozen column thing broken or why this happens?

**Comment by alump** [comment]
last-frozen is added to last in DOM tree, but that not the last in presentation. So line is drawn to wrong place. Regression (I think), so tagging as Q4 2017.

**Comment by alump** [comment]
Way to reproduce in basic demo:
- Freeze first column
- Freeze second column (will become first)
- Now horizontal scroll

Actual outcome:
Border is shown after 1st column from left

Expected outcome:
Border should be shown after 2nd column from left, as two columns are frozen

**Comment by alump** [comment]
If this is fixed, it might require something extra to PR https://github.com/vaadin/px-data-grid/pull/584

**Comment by alump** [comment]
Did my own try to fix it, by using sanity checker I added for other reasons. See PR #584
