### ISSUE TITLE
Advanced Filtering: "Cancel" and "Apply" buttons use the wrong horizontal spacing

### ISSUE THREAD

**Issue by vonsichart200** [vaadin/px-data-grid#588]
Current:
Horizontal spacing is 25px

Expected:
Horizontal spacing is 10px

![screen shot 2018-02-05 at 12 31 30 pm](https://user-images.githubusercontent.com/25111262/35827450-f05b8614-0a70-11e8-8ace-acd47c4f705f.png)

**Comment by alump** [comment]
Already fixed in next release

**Comment by alump** [comment]
I think all spacing here is from px-modal, not from our side.

**Comment by alump** [comment]
Had to fix with -7px margin, as px-modal adds about 20px of padding there.
