### ISSUE TITLE
Advanced Filtering: Selecting the overflow chip, triggers the zero state overlaid on top of filter modal

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#601]
## Description

Creating multiple filters set, will generate the overflow chip as expected.
Selecting the overflow chip is supposed to open the filter modal with all the filters that have been applied. However, it looks like it first opens the zero state modal overlaid on top of the actual filter modal.

Wasn't able to reproduce this in the demo, but the test file below reproduces the problem every time you add a filter and select the overflow chip.

## Version
Data-grid: V1.1.11

## Screenshot
![screen shot 2018-02-06 at 5 24 08 pm](https://user-images.githubusercontent.com/10835611/35893512-42cbb3d6-0b63-11e8-9c84-52f85212c96c.png)

## Code
https://gist.github.com/ppeyro/7f41242a648c807a5d233b2651cbc003

**Comment by alump** [comment]
@toshegg - did we do something really wrong here?

**Comment by alump** [comment]
This only happens if you have two px-data-grids on same page, if you remove the second it will only pop up one. Do we use some global variable by mistake?

**Comment by alump** [comment]
Maybe the issue here is that ID is same, and px-modal just copies it to body attached to modal element, and then uses it find instance. So we would need to generate some unique ID for px-modal element?

**Comment by alump** [comment]
@toshegg - provided my fix in PR, please review and improve if required
