### ISSUE TITLE
Advanced Filtering: Unable to change the condition based on column type

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#610]
## Description

If a column is a number column, in advanced filter modal the condition dropdown should change its items to (less than/equal/not equal/etc…) instead of the default (equals, contains, starts with/etc..).  

I've seen the condition dropdown items change based on the column type in the demo.  I don't see any specific code in the demo code that swaps the dropdown items so assumed it must be based on the column type?   But I can't get it to happen automatically based on the column type in my test grid (Gist link below). Unsure, if there is a specific attribute that enables swapping the dropdown based on the column type or if something else is needed to get that to work.

## Version
Datagrid: V1.1.11

### In demo, dropdown items change based on column type
![screen shot 2018-02-07 at 10 36 03 am](https://user-images.githubusercontent.com/10835611/35935593-c9e395fe-0bf5-11e8-8b85-586c18523967.png)

### In test grid, no item change even though the column is type number
![screen shot 2018-02-07 at 10 36 16 am](https://user-images.githubusercontent.com/10835611/35935630-e51dd8e8-0bf5-11e8-95f0-6c32a3972c4a.png)

## Code
https://gist.github.com/ppeyro/4f15e03cf14345f14caef059c9a7c8aa

**Comment by alump** [comment]
@toshegg - how to define the column as number type. Is it clear in documentation?

**Comment by toshegg** [comment]
@alump, seems like so:

https://github.com/vaadin/px-data-grid/blob/f8717511a9f62bccce829de2c622c5d79ace9e63/px-data-grid.html#L338

@ppeyro, it doesn't happen automatically for generated columns. In order to do that you need to pass columns manually.

**Comment by ppeyro** [comment]
@toshegg Thanks, will try it that way. I assume as long as it's defined as a number col, it'll work as expected?  If it does, we should doc this more clearly.  I'll make a note of it for our documentation.

**Comment by ppeyro** [comment]
@toshegg Thanks, verified if the column type is set to "number", the condition in filter switches to the correct dropdown in filter.  Made a note to add this to our developer guide later on.
```
{
            "name":"Temp",
            "type": "number",
            "path":"Temp",
            "hidden":false,
            "editable":true,
            "frozen":false,
            "id":"Temp[number]",
            "renderer":"px-data-grid-number-renderer"
          },
