### ISSUE TITLE
Pencil "Edit Affordance" appears only on click in Safari

### ISSUE THREAD

**Issue by vonsichart200** [vaadin/px-data-grid#627]
1. Open Demo 1.11 in Safari
2. Choose "Custom Columns"
3. Enable "EDITABLE" 
4. Hover over the rows. -> Pencil icon does not appear
5. Click on a row -> Pencil icon appears

**Comment by alump** [comment]
Looks like Safari doesn't like to pass hover magic over shadow dom boundaries. While even IE11 does this. Only way to fix this would be to do custom JS hack for Safari, but that would cause more issues than it resolves.
