### ISSUE TITLE
Advanced Filtering:  Slider not sliding in FF58

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#632]
## Description

This seems to be unique to FF58. (IE11 has other issues with the slider in modal, so putting that in a separate issue).
When you have the slider present as a value selector in the filter modal, selecting the handles to slide it doesn't work. Left handle doesn't slide at all and the right handle will snap handle to snap back to zero.

## Version
Data-grid: V1.1.11
Browser: FF58

### Initial State
![screen shot 2018-02-08 at 5 36 32 pm](https://user-images.githubusercontent.com/10835611/36007346-e8047808-0cf6-11e8-8444-f24a8cc13755.png)

### After selecting the right handle
![screen shot 2018-02-08 at 5 36 39 pm](https://user-images.githubusercontent.com/10835611/36007362-f95216ce-0cf6-11e8-95e7-5d0f2efac0f6.png)

## Code
https://gist.github.com/ppeyro/49720f84b63d0d40818724c8a7a217d0

**Comment by alump** [comment]
@toshegg check this

**Comment by alump** [comment]
This is issue with px-slider. It doesn't work with Firefox when it's inside px-modal. Easy code to see the issue without any of px-data-grid components is here: https://gist.github.com/alump/2d1d4d427f0f20f8ea9b772d415962fb

Just copy that to suitable HTML (the gist you gave above is fine) and you will see that slider is broken.

@ppeyro

**Comment by alump** [comment]
Dependency: https://github.com/PredixDev/px-slider/issues/29

**Comment by nonmetalhail** [comment]
This has been fixed in slider v2.2.2

**Comment by alump** [comment]
@limonte - can you update dependency, and try it on firefox

**Comment by andrealperry** [comment]
Need for Beta

**Comment by limonte** [comment]
Tested with the latest px-slider, works fine in Firefox 58.
