### ISSUE TITLE
Advanced Filtering: Slider not rendering in modal in IE11

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#634]
## Description

Slider is not rendering at all in the filter modal in IE11. Same test file renders the slider in other browsers.
Not sure if this is a side effect of the theming issue, tracked in issue#626.

## Version
Data-grid: V1.1.11
Browser: IE11

## Screenshot
![screen shot 2018-02-08 at 6 03 11 pm](https://user-images.githubusercontent.com/10835611/36008106-844e52da-0cfa-11e8-84aa-325ce120c20d.png)

## Code
https://gist.github.com/ppeyro/49720f84b63d0d40818724c8a7a217d0

**Comment by alump** [comment]
@toshegg - check this, make sure https://github.com/vaadin/px-data-grid/pull/625 in before you test.

**Comment by alump** [comment]
@limonte - is this fixed, i think it is

**Comment by ppeyro** [comment]
@alump This is fixed in V1.2.1. Closing it out.

**Comment by ppeyro** [comment]
Should have mentioned, the slider works in IE11 with V1.2.1 but its color/theme is different than other browsers. Reopening just to verify this specific issue remaining.
Here are screenshots comparing IE11 vs. FF58
![2018-02-13_0920](https://user-images.githubusercontent.com/10835611/36163965-c8af27e4-109f-11e8-8df2-3dbfeb84de36.png)
![screen shot 2018-02-13 at 9 24 37 am](https://user-images.githubusercontent.com/10835611/36163969-cd3e27c4-109f-11e8-963f-b027a3181974.png)

**Comment by alump** [comment]
We do not define colors of px-slider anyway, so nothing we can do for those colors.
