### ISSUE TITLE
Advanced Filtering: Dropdown cutoff

### ISSUE THREAD

**Issue by andrealperry** [vaadin/px-data-grid#637]
v1.1.11

**Dropdown is being cutoff and is not scrollable:**
![screen shot 2018-02-09 at 9 34 20 am](https://user-images.githubusercontent.com/30873778/36044512-c59a0cb0-0d87-11e8-9b96-da92493194ef.png)

**Comment by ppeyro** [comment]
@andrealperry This is the overlay issue, tracked in issue #527.  Elliot is working on this.

**Comment by andrealperry** [comment]
Needed for beta - can we close?

**Comment by nonmetalhail** [comment]
fixed in dropdown v4.6.x
