### ISSUE TITLE
Advanced Filtering: Expose "Save this filter set" as a property in demo

### ISSUE THREAD

**Issue by andrealperry** [vaadin/px-data-grid#638]
Expose "Save this filter set" as a property toggle in demo.
![screen shot 2018-02-09 at 11 00 35 am](https://user-images.githubusercontent.com/30873778/36044760-8531ddd2-0d88-11e8-85d7-48e04e6d1e9f.png)

**Comment by alump** [comment]
@andrealperry  Did you have ```offer-filter-saving``` attribute enabled? Not all applications will want to offer saving, so if application doesn't ask for it. it will not be shown.

**Comment by alump** [comment]
Basic demo already has toggle for this:
![toggle](https://user-images.githubusercontent.com/1378660/36049069-4d4ce548-0d96-11e8-9407-0f7a140041c3.png)

**Comment by andrealperry** [comment]
Got it, I didn't see it before. Thanks, Sami. Please close.
