### ISSUE TITLE
Advanced Filter: Slider in advanced filter broke in V1.2.0

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#647]
## Description

This looks like a regression. The test file below in V1.1.11 is working when setting up a filter with a slider but causes an error in V1.2.0 and the slider doesn't render at all.

## Version
Data-grid: V1.2.0
Browser: Chrome

## Screenshots
![screen shot 2018-02-12 at 3 10 55 pm](https://user-images.githubusercontent.com/10835611/36125154-c0bb87dc-1007-11e8-9c7c-509bad8525f4.png)

![screen shot 2018-02-12 at 3 12 13 pm](https://user-images.githubusercontent.com/10835611/36125157-c51d8406-1007-11e8-9d64-9cb8fcfc7b23.png)

## Code

https://gist.github.com/ppeyro/4c6e5620672bd5e3237abe416e7f85e8

**Comment by alump** [comment]
@ppeyro - was this fixed with 1.2.1?

**Comment by ppeyro** [comment]
This is fixed in 1.2.1. Closing
