### ISSUE TITLE
Editing: date+time columns don't retain their original value when it pops into edit mode.

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#662]
## Description

In Date+time columns, if you select to edit, the original value is replaced with today's date in edit mode and the time changes to 0's.  This is only an issue with Date+time fields, date fields retain their original value.

You can reproduce in the demo as well as test files.

## Version
Data-grid: V1.2.3

## Screenshots
![screen shot 2018-02-13 at 6 35 14 pm](https://user-images.githubusercontent.com/10835611/36185293-2f393cc8-10ed-11e8-8827-aba1fff8a5fb.png)

![screen shot 2018-02-13 at 6 35 20 pm](https://user-images.githubusercontent.com/10835611/36185309-44eefdb4-10ed-11e8-9835-8e35238861e5.png)

**Comment by alump** [comment]
I think this wasn't 1.2.3 when tested, the demo does not match version in 1.2.3. In 1.2.3 your editors should match the presentation.

**Comment by ppeyro** [comment]
One too many switches between tags last night. It landed me on the wrong tag( 1.2.2) when I thought I was on V1.2.3.  All is well with V1.2.3 and edit retaining its original dates. Closing.
