### ISSUE TITLE
Groupby Date columns: Editing then sorting, splits the row of the group

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#664]
## Description

This is a mind twister and seems specific to grouping based on a"date" column.
Here are the steps:
1. Groupby a date column, e.g. maintenance date in example below
2. Edit any cell in a group that has multiple rows, then save. (This is essential, if you don't edit  a cell, the group stays in-tact)
3. Now sort based on any column.
4. Notice the edited row splits out of the group it originally belonged to into a group by itself.

## Version

Data-grid: V1.2.3
Browser: Chrome

## Screenshots
![screen shot 2018-02-14 at 11 00 17 am](https://user-images.githubusercontent.com/10835611/36222544-720ef50e-1176-11e8-9082-e57f9ef6ac89.png)

![screen shot 2018-02-14 at 10 48 15 am](https://user-images.githubusercontent.com/10835611/36222110-1dfe35c0-1175-11e8-9ae2-cd9f7e22a10f.png)
![screen shot 2018-02-14 at 10 48 46 am](https://user-images.githubusercontent.com/10835611/36222122-24ecbe60-1175-11e8-99a8-7b8b046a80d9.png)

## Code
https://gist.github.com/ppeyro/82aa5fd82f9a641023fd50488461b8d8

**Comment by alump** [comment]
with PR we current have this shouldn't happen anymore, editing in group by mode shouldn't anymore cause move between groups (until reload, resort or other event happens)

**Comment by ppeyro** [comment]
Verified the fix in V1.2.4. No longer splitting the group into 2 after edit.
