### ISSUE TITLE
Visual Enhancement: Filter columns need more space in between each other

### ISSUE THREAD

**Issue by vonsichart200** [vaadin/px-data-grid#667]
**Current:**
- Columns have 7 px space between each other horizontally
- Rows have 7px space between each other vertically
- "X" is 7 pixels away from the row

**Expected:**
- Columns have 10px space between them
- Rows have 10px space between each other vertically
- "X" is 20 pixels away from the row
(px-data-grid_filtering_v6-1_ap.pdf - Page 10)

![screen shot 2018-02-14 at 2 06 20 pm](https://user-images.githubusercontent.com/25111262/36230862-a7cc9f7e-1190-11e8-8e2e-8db0cc799664.png)

**Comment by andrealperry** [comment]
Nice to have
