### ISSUE TITLE
Visual Enhancement: Edit mode's checkmark btn icon appears larger in IE11

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#668]
## Description

IE11 special cosmetic issue:
When in edit mode, checkmark button icon appears larger than the cancel icon next to it.

## Version
Data-grid: V1.2.3
Browser: IE11

## Screenshot
![2018-02-14_1311](https://user-images.githubusercontent.com/10835611/36229359-cdeaf2c8-118b-11e8-83d3-4a25fe00565f.png)

**Comment by alump** [comment]
Can you @limonte check this out, i spent 20mins with this can couldn't figure out why this doesn't work in IE. It's is inside dom-if, but it gets the border with rounding and everything but icon rules it doesn't get. Feels like I just can't give icon size for px-icon inside dom-if template, so do we just need to hard code the property into this button somehow?

The cancel button next to it is little different, as that column only has button, so it's not inside dom-if, just one button that changes it behavior (and that actually works in IE11 somehow).
