### ISSUE TITLE
Demo/IE11: Double scrollbar when opening the property editor in demos.

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#669]
## Description

Another IE11 special:  
When the property Editor in the demo files is opened in IE11, there is a double vertical scrollbar but you can't scroll up/down the content of the file to view/edit using the inner vertical scrollbar; however, touchpad works for scrolling.
Most visible with table-data editor that contains large content in basic examples/more rows tab demo.

For what it's worth, this is currently the case with other components as well.

## Version
Data-grid: V1.2.3
Browser: IE11

## Screenshot
![2018-02-14_1230](https://user-images.githubusercontent.com/10835611/36229570-9072241a-118c-11e8-882b-6400988a1a47.png)

**Comment by alump** [comment]
@ppeyro This is px-demo issue since px-modal was changed, We don't do anything for that part of UI, so reopen bug there, thanks.

**Comment by ppeyro** [comment]
That was meant for us to fix later, that's why I marked the summary with "Demo".  Could you please reopen and label it as external dependency/GE response? Thanks.

**Comment by alump** [comment]
There is nothing to fix on our side.

**Comment by alump** [comment]
Closing
