### ISSUE TITLE
Advanced Filtering: Gray line artifacts found after adding filters

### ISSUE THREAD

**Issue by andrealperry** [vaadin/px-data-grid#671]
Gray line artifacts found after adding filters and hovering over the input field.

![screen-shot-2018-02-14-at-2 16 38-pm](https://user-images.githubusercontent.com/30873778/36231175-eac1d406-1191-11e8-8133-e1206d6a2097.png)

**Comment by alump** [comment]
I think this is done by your default input theming, we are not adding any special styling to input fields as far as I know.

**Comment by limonte** [comment]
I can't reproduce this.

@andrealperry please specify the OS and browser you're using.

**Comment by andrealperry** [comment]
Nice to have

**Comment by limonte** [comment]
Looks like the duplicate of https://github.com/vaadin/px-data-grid/issues/670

If so, please close this so we can keep the communication in one place.
