### ISSUE TITLE
Usability: "Resizable" and contextual column menu don't seems to work at the same time

### ISSUE THREAD

**Issue by vonsichart200** [vaadin/px-data-grid#673]
**Current:**
When the user hovers over the three dots, they disappear in order to show the column resizing cursor.

**Expected:**
When the user hovers over the three dots he is able to click them and the contextual menu appears. The resizing cursor should appear just a little on the left of it.

**Comment by alump** [comment]
"just a little on the left of it" needs more clarification @vonsichart200
