### ISSUE TITLE
Groupby: Edit on hover should be disabled at the group level

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#675]
## Description

When the grid is in groupby mode without the groups being expanded, if you hover over the top level group, you'll get the edit icon.  Selecting the edit would cause other interesting side effects.

Saw this in my test files but was able to reproduce in custom-columns demo as well.

## Version
Data-grid: V1.2.3
Browser: Chrome, IE11 (doesn't happen in FF)

## Screenshots
![screen shot 2018-02-14 at 2 56 17 pm](https://user-images.githubusercontent.com/10835611/36232678-9766f6d2-1197-11e8-8338-c76e65f8c200.png)

![screen shot 2018-02-14 at 2 56 22 pm](https://user-images.githubusercontent.com/10835611/36232682-9aafaec4-1197-11e8-9911-46a6aa790848.png)

**Comment by alump** [comment]
Please retest with 1.2.4 @ppeyro

**Comment by ppeyro** [comment]
Verified in 1.2.4, hovering over the top level group no longer triggers the edit icon. Closing.
