### ISSUE TITLE
Advanced Filtering: Use “Sentence case” for dropdown list items

### ISSUE THREAD

**Issue by andrealperry** [vaadin/px-data-grid#677]
Spec Version 4, 2018-1-25
Use Sentence case for dropdown list items. 

For example:	
"Full Name" - incorrect
"Full name" - correct								

**Current state**
![screen shot 2018-02-14 at 3 21 07 pm](https://user-images.githubusercontent.com/30873778/36233477-1c5ae97c-119b-11e8-8397-4f68a58b9308.png)

![screen shot 2018-02-14 at 3 21 38 pm](https://user-images.githubusercontent.com/30873778/36233482-26679136-119b-11e8-8193-75b76c5eb82f.png)

**Expected state**
<img width="951" alt="screen shot 2018-02-14 at 3 23 05 pm" src="https://user-images.githubusercontent.com/30873778/36233492-30d572aa-119b-11e8-9d8a-37fb84a621e2.png">

<img width="950" alt="screen shot 2018-02-14 at 3 23 13 pm" src="https://user-images.githubusercontent.com/30873778/36233498-34d035f2-119b-11e8-85fd-f39b2ee89d85.png">

**Comment by alump** [comment]
Columns names are show exactly as those are given by application. Just see the basic demo. Do you want us to force first character capital, and force the rest lower case or something else? Sorry, please clarify. If you open the column definition, and change the casing and then reopen the filter dialog. In header of table all text is uppercased as request, elsewhere the original writing is used.

Fixing the conditions...

**Comment by alump** [comment]
@andrealperry - column names are configurable by application, so in this case fix the test application to give column headers in right casing.

**Comment by andrealperry** [comment]
Thanks, Sami. Gotcha, the column names are provided by the application. However, the column name examples in the demo should reflect "Sentence case" whether that is done by Vaadin or GE.

**Comment by alump** [comment]
Separate fix to demo cases will follow soon, anyway the final demos will not be these demos we have right now.
