### ISSUE TITLE
Advanced Filter: "custom" option should be removed from condition dropdown

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#682]
## Description

When you have dateRanges attribute in a date column to customize the time range,  the condition's dropdown (Time Range) in advanced filter modal automatically adds a "Custom" as an option to the end of the dropdown.  That should be disabled per design.

## Version
Data-grid: 1.2.4

## Screenshot
![screen shot 2018-02-15 at 3 06 15 pm](https://user-images.githubusercontent.com/10835611/36285865-23d8dbb0-1262-11e8-8b21-9fa7cee7d678.png)

![screen shot 2018-02-15 at 3 09 24 pm](https://user-images.githubusercontent.com/10835611/36285945-5bd65470-1262-11e8-9b65-f7ce414807a7.png)

![screen shot 2018-02-15 at 3 14 52 pm](https://user-images.githubusercontent.com/10835611/36286114-142f4b58-1263-11e8-8dea-abe10e79fd01.png)

**Comment by andrealperry** [comment]
Needed for GA
