### ISSUE TITLE
Advanced Filter: Filter chip's date format should match column displayFormat.

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#683]
## Description

This is a visual future enhancement and should also be reviewed by the design team.

If you specify the displayFormat for a date column to be:  
```"rendererConfig":{
              "dataFormat": "YYYY-MM-DD HH:mm:ss",
              "displayFormat": "MM-DD-YYYY HH:mm:ss"
            }
```
The resulting format in the grid is MM-DD-YYYY as expected; however, the filter chip formats the date as YYYY/MM/DD.

Note #1:  "/ " in filter chip should be changed to "-" 
Note#2:  Date format in filter chip defaults to ISO format.

## Version
Data-grid: V1.2.4

## Screenshot
![screen shot 2018-02-15 at 3 20 06 pm](https://user-images.githubusercontent.com/10835611/36286511-fbf883e0-1264-11e8-8fac-e80dbb7040cf.png)

**Comment by andrealperry** [comment]
Needed for GA
