### ISSUE TITLE
1.7 Auto wrap text

### ISSUE THREAD

**Issue by limonte** [vaadin/px-data-grid#8]
Functionality of `<iron-list>` will be used to allow auto wrapping of text inside columns when width of column is less than width of content inside it.

There will be the ability in to allow the application to customize a column to prevent the text to auto wrap.

![image](https://user-images.githubusercontent.com/6059356/32549686-10242362-c493-11e7-9d09-822edb626212.png)

An example for this functionality will be provided in the scope of #7

**Comment by alump** [comment]
demo needed

**Comment by limonte** [comment]
Done, demonstrated in the remote-data-source demo.
