### ISSUE TITLE
DESIGN REVIEW: Deliverable 1 Feedback from GE

### ISSUE THREAD

**Issue by Aileen-H** [vaadin/px-data-grid#89]
[Vaadin Delivery 1 Feedback 2017-11-28.pdf](https://github.com/vaadin/px-data-grid/files/1515217/Vaadin.Delivery.1.Feedback.2017-11-28.pdf)

**Comment by alump** [comment]
Assigning to me, I need to split this to separate issues, as we will not most likely get all fixed in single delivery.

**Comment by alump** [comment]
I think this is done now. Scrollbar position change is just too large to do now.
