### ISSUE TITLE
Highlight doesn't work if table data is set first

### ISSUE THREAD

**Issue by davidrleonard** [vaadin/px-data-grid#90]
If `tableData` is defined and the cells are rendered before `highlight` is defined, the highlight rules are never applied.

Example:

```html
<px-data-grid></px-data-grid>
<script>
  var grid = document.querySelector('px-data-grid');
  grid.tableData = [
    {first: "Elizabeth", last: "Wong",email: "sika@iknulber.cl"},
    {first: "Jeffrey", last: "Hamilton",email: "cofok@rac.be"},
    {first: "Alma", last: "Martin",email: "dotta@behtam.la"},
    {first: "Carl", last: "Saunders",email: "seh@bibapu.gy"},
    {first: "Willie", last: "Dennis",email: "izko@dahokwej.ci"}
  ];
  /* Artificial wait to simulate app grabbing highlight rules from server */
  setTimeout(() => {
    grid.highlight = [
      {
        type: 'cell',
        condition: (cellContent, column, item) => cellContent === 'Wong'
      }
    ];
  }, 1000);
</script>
```

I think the issue is here: https://github.com/vaadin/px-data-grid/blob/baedb4d011b541db2f3b12c8a236c645f708322c/px-data-grid.html#L103

`highlight` is not passed to the `_getCellStyle` method in the template, so it doesn't re-run when highlight is defined or changed.

Highlight is also treated as static here, if it is defined after `ready` this bit of code won't re-run: https://github.com/vaadin/px-data-grid/blob/baedb4d011b541db2f3b12c8a236c645f708322c/px-data-grid.html#L386-L389

**Comment by alump** [comment]
Yes, this is valid bug. We need to force redraw of content when highlight property changes. That is currently missing. Marking it to deliverable 3, but if done before delivery 2, please update milestone.

**Comment by alump** [comment]
Can not reproduce this bug in test cases, not sure it has been fixed by all the changes we have done, or am I doing something wrong. The part in ready function is mystery to me, I need to ask @Toshegg why it's there.

**Comment by alump** [comment]
I was trying to make test for this, but it was working, but did not have enough time to verify it really works.

**Comment by limonte** [comment]
Fixed, https://jsfiddle.net/8ojpmj5q/
